- platform: alexa_media
  name: alexa_media

- platform: group
  name: all devices
  services:
    - service: notify.mobile_app_sm_g960f
    - service: notify.mobile_app_iphone_van_stephanie
    - service: notify.mobile_app_iphone_van_lucas
    - service: notify.mobile_app_timo_s_oneplus
