- platform: alexa_media
  name: alexa_media

- platform: group
  name: all devices
  services:
    - service: mobile_app_sm_g986b
    - service: mobile_app_iphone_van_stephanie
    - service: mobile_app_iphone_van_lucas
    - service: mobile_app_timo_s_oneplus
