homeassistant:
  customize: !include_dir_merge_named ../customizations/entities

  # Configure a default setup of Home Assistant (frontend, api, etc)
  default_config:

  auth_mfa_modules:
    - type: totp
  whitelist_external_dirs:
    - /config