homeassistant:
  customize: !include configuration/customize.yaml

  # Configure a default setup of Home Assistant (frontend, api, etc)
  default_config:

  auth_mfa_modules:
    - type: totp
  whitelist_external_dirs:
    - /config