custom_header:
  kiosk_mode: true
  footer_mode: true
  reverse_tab_direction: true

decluttering_templates:
  !include lovelace/decluttering_templates/decluttering_templates.yaml

title: Home
views:
  - path: default_view
    title: Home
    icon: 'mdi:home-assistant'
    cards:
      - type: 'custom:state-switch'
        entity: user
        states:
          Dennis:
            type: horizontal-stack
            cards:
              - type: markdown
                style: |
                  ha-card {
                    margin: 5px 14px -5px 10px;
                  }
                  h2 {
                    font-size: 20px;
                    font-weight: 500;
                    color: var(--app-header-text-color);
                  }
                content: |
                  {% if now().hour < 5 %}
                  ## Good night
                  {% elif now().hour < 12 %}
                  ## Good morning
                  {% elif now().hour < 18 %}
                  ## Good afternoon
                  {% else %}
                  ## Have a nice evening
                  {% endif %}
              - type: picture
                style: |
                  ha-card {
                    max-width: 36px;
                    margin-left: auto;
                    margin-right: 20px;
                    margin-top: 14px;
                    box-shadow: none;
                  }
                image: /local/images/dennis-square.jpg
          Stephanie:
            type: vertical-stack
            cards:
              - type: markdown
                content: |
                  {% if now().hour < 5 %}
                  ## Good night
                  {% elif now().hour < 12 %}
                  ## Good morning
                  {% elif now().hour < 18 %}
                  ## Good afternoon
                  {% else %}
                  ## Have a good evening
                  {% endif %}
                style: |
                  ha-card {
                    margin: 0px 14px -5px 14px;
                  }
                  h2 {
                    font-size: 20px;
                    font-weight: 500;
                    color: var(--app-header-text-color);
                  }
              - type: picture
                style: |
                  ha-card {
                    max-width: 36px;
                    margin-left: auto;
                    margin-right: 20px;
                    margin-top: -50px;
                    box-shadow: none;
                  }
                image: /local/images/stephanie-square.jpg
          Lucas:
            type: vertical-stack
            cards:
              - type: markdown
                content: |
                  {% if now().hour < 5 %}
                  ## Good night
                  {% elif now().hour < 12 %}
                  ## Good morning
                  {% elif now().hour < 18 %}
                  ## Good afternoon
                  {% else %}
                  ## Have a good evening
                  {% endif %}
                style: |
                  ha-card {
                    margin: 0px 14px -5px 14px;
                  }
                  h2 {
                    font-size: 20px;
                    font-weight: 500;
                    color: var(--app-header-text-color);
                  }
              - type: picture
                style: |
                  ha-card {
                    max-width: 36px;
                    margin-left: auto;
                    margin-right: 20px;
                    margin-top: -50px;
                    box-shadow: none;
                  }
                image: /local/images/lucas-square.jpg
          Timo:
            type: vertical-stack
            cards:
              - type: markdown
                content: |
                  {% if now().hour < 5 %}
                  ## Good night
                  {% elif now().hour < 12 %}
                  ## Good morning
                  {% elif now().hour < 18 %}
                  ## Good afternoon
                  {% else %}
                  ## Have a good evening
                  {% endif %}
                style: |
                  ha-card {
                    margin: 0px 14px -5px 14px;
                  }
                  h2 {
                    font-size: 20px;
                    font-weight: 500;
                    color: var(--app-header-text-color);
                  }
              - type: picture
                style: |
                  ha-card {
                    max-width: 36px;
                    margin-left: auto;
                    margin-right: 20px;
                    margin-top: -50px;
                    box-shadow: none;
                  }
                image: /local/images/timo-square.jpg
      - type: vertical-stack
        cards:
          - type: markdown
            content: |
              {% if now().month in (1,) %}
              ## January {{ now().day }}
              {% elif now().month in (2,) %}
              ## February {{ now().day }}
              {% elif now().month in (3,) %}
              ## March {{ now().day }}
              {% elif now().month in (4,) %}
              ## April {{ now().day }}
              {% elif now().month in (5,) %}
              ## May {{ now().day }}
              {% elif now().month in (6,) %}
              ## June {{ now().day }}
              {% elif now().month in (7,) %}
              ## July {{ now().day }}
              {% elif now().month in (8,) %}
              ## August {{ now().day }}
              {% elif now().month in (9,) %}
              ## September {{ now().day }}
              {% elif now().month in (10,) %}
              ## October {{ now().day }}
              {% elif now().month in (11,) %}
              ## November {{ now().day }}
              {% elif now().month in (12,) %}
              ## December {{ now().day }}
              {% endif %}
            style: |
              ha-card {
                margin: 12px 14px -5px 14px;
              }
              h2 {
                font-size: 18px;
                font-weight: 400;
                padding-left: 10px;
                border-left: 3px solid rgba(81, 134, 236);
              }
          - type: 'custom:state-switch'
            entity: weather.lopik_cabauw
            default: default
            states:
              sunny:
                type: 'custom:simple-weather-card'
                style: |
                  ha-card {
                    box-shadow: var(--card-box-shadow);
                    margin: 0px 14px 15px 14px;
                  }
                entity: weather.dark_sky
                name: at home
                secondary_info: precipitation
                tap_action:
                  action: more-info
                  cards: null
                backdrop:
                  day: 'rgba(249, 233, 181)'
                  text: var(--app-header-text-color)
                  night: 'rgba(76, 87, 110)'
                  fade: true
              default:
                type: 'custom:simple-weather-card'
                style: |
                  ha-card {
                    box-shadow: var(--card-box-shadow);
                    margin: 0px 14px 15px 14px;
                  }
                entity: weather.lopik_cabauw
                name: at home
                secondary_info: precipitation
                tap_action:
                  action: more-info
                  cards: null
                backdrop:
                  day: 'rgba(159, 193, 249)'
                  text: var(--app-header-text-color)
                  night: 'rgba(76, 87, 110)'
                  fade: true
      - type: vertical-stack
        cards:
          - type: markdown
            content: |
              ## Access
            style: |
              ha-card {
                margin: 0px 14px -5px 14px;
              }
              h2 {
                font-size: 18px;
                font-weight: 400;
                padding-left: 10px;
                border-left: 3px solid rgba(81, 134, 236);
              }
          - type: entities
            style: |
              ha-card {
                --paper-card-background-color: var(--sidebar-background-color);
                box-shadow: var(--card-box-shadow);
                margin: 0px 14px 5px 14px;
              }
            show_header_toggle: false
            title: null
            entities:
              - lock.schlage_allegion_be469_touchscreen_deadbolt_locked
              - entity: cover.garage_door_opener
                type: 'custom:secondaryinfo-entity-row'
                secondary_info: '[[ cover.garage_door_opener.state ]]'
              - entity: switch.gate_opener
                type: 'custom:secondaryinfo-entity-row'
                secondary_info: >-
                  [[ if(input_boolean.latch_gate.state == "on", "Latched",
                  "Press/hold to latch open") ]]
                deep_press: true
                hold_action:
                  haptic: heavy
                  action: call-service
                  service: input_boolean.toggle
                  service_data:
                    entity_id: input_boolean.latch_gate
              - alarm_control_panel.konnected_alarm
      - type: vertical-stack
        cards:
          - type: 'custom:auto-entities'
            show_empty: false
            card:
              type: markdown
              content: |
                ## At a Glance
              style: |
                ha-card {
                  margin: 0px 14px -5px 14px;
                }
                h2 {
                  font-size: 18px;
                  font-weight: 400;
                  padding-left: 10px;
                  border-left: 3px solid rgba(81, 134, 236);
                }
            filter:
              include:
                - entity_id: '*door*'
                  state: Open
                - entity_id: '*door'
                  state: 'on'
                - entity_id: '*window*'
                  state: 'on'
                - name: '/[Ll]ight/'
                  not:
                    domain: input_boolean
                  state: 'on'
                - name: '/[Ff]an/'
                  not:
                    domain: automation
                  state: 'on'
                - state: Running
                - state: unlocked
                - state: 'Yes'
                - entity_id: '*osm'
                  not:
                    state: Home
              exclude:
                - name: '/[Cc]amera/'
                - entity_id: light.kitchen_light_level
                - entity_id: light.flux_led_strip
                - entity_id: light.kitchen_light_2_level
          - type: 'custom:auto-entities'
            show_empty: false
            card:
              type: entities
              style: |
                ha-card {
                  --paper-card-background-color: var(--sidebar-background-color);
                  box-shadow: var(--card-box-shadow);
                  margin: 0px 14px 5px 14px;
                }
              show_header_toggle: false
            filter:
              include:
                - entity_id: '*door*'
                  state: Open
                - entity_id: '*door'
                  state: 'on'
                - entity_id: '*window*'
                  state: 'on'
                - name: '/[Ll]ight/'
                  not:
                    domain: input_boolean
                  state: 'on'
                - name: '/[Ff]an/'
                  not:
                    domain: automation
                  state: 'on'
                - state: Running
                - state: unlocked
                - state: 'Yes'
                - entity_id: '*osm'
                  not:
                    state: Home
              exclude:
                - name: '/[Cc]amera/'
                - entity_id: light.kitchen_light_level
                - entity_id: light.flux_led_strip
                - entity_id: light.kitchen_light_2_level
