- platform: template
  switches:
    living_room_away:
      friendly_name: Living Room Away
      value_template: "{{(states.climate.living_room_2.attributes|default({})).away_mode|default('off') == 'on'}}"
      turn_on:
        - service: climate.set_away_mode
          data:
            entity_id: climate.living_room_2
            away_mode: 'True'
      turn_off:
        - service: climate.set_away_mode
          data:
            entity_id: climate.living_room_2
            away_mode: 'False'
    security_armed:
      friendly_name: Home Security Arm
      value_template: "{{states('alarm_control_panel.konnected_alarm') != 'disarmed'}}"
      turn_on:
        - service: alarm_control_panel.alarm_arm_away
          entity_id:
            - alarm_control_panel.konnected_alarm
      turn_off:
        - service: alarm_control_panel.alarm_disarm
          entity_id:
            - alarm_control_panel.konnected_alarm
