---
# This is actually just a bootstrap for my Lovelace configuration.

# It loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarentee the order of
# the tabs of the view in the UI.
#
title: Les Jambons
resources:
  - url: /community_plugin/lovelace-auto-entities/auto-entities.js
    type: js
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/calendar-card/calendar-card.js
    type: js
  - url: /community_plugin/lovelace-card-loader/card-loader.js
    type: js
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: js
  - url: /community_plugin/check-button-card/check-button-card.js
    type: module
  - url: /community_plugin/decluttering-card/decluttering-card.js
    type: module
  - url: /community_plugin/light-entity-card/light-entity-card.js
    type: js
  - url: /community_plugin/lovelace-markdown-mod/markdown-mod.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
  - url: /community_plugin/lovelace-more-info-card/more-info-card.js
    type: js
  - url: /community_plugin/lovelace-postnl-card/postnl-card.js
    type: module
  - url: /community_plugin/simple-weather-card/simple-weather-card-bundle.js
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /community_plugin/lovelace-state-switch/state-switch.js
    type: js
  - url: /community_plugin/sun-card/sun-card.js
    type: module
  - url: /community_plugin/swipe-card/swipe-card.js
    type: module
  - url: /community_plugin/thermostat-card/thermostat-card.js
    type: module
  - url: /community_plugin/upcoming-media-card/upcoming-media-card.js
    type: js
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/lovelace-weather-card-chart/weather-card-chart.js
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module

views:
  - !include lovelace/views/dashboard.yaml
  - !include lovelace/views/downstairs.yaml
  - !include lovelace/views/upstairs.yaml
  - !include lovelace/views/outside.yaml
  - !include lovelace/views/security.yaml
  - !include lovelace/views/system.yaml