title: Les Jambons
background: var(--background)
views:
  - !include lovelace/00_home_view.yaml
  - !include lovelace/05_light_view.yaml
  - !include lovelace/10_media_view.yaml
  - !include lovelace/20_system_graphs.yaml
