# Custom Card Resources
resources:
  !include lovelace-dev/resources/resources.yaml
 
# Compact Custom Header
# You will need to hide views if you want to
# have views that behave like popup cards!
cch:
  !include lovelace-dev/cch/compact-custom-header.yaml # Changed/Added in 0.12.0, this is now separated from this file to lovelace-dev/cch/

# Decluttering Templates
# These are the templates used to avoid too much
# duplicate code.
decluttering_templates:
  !include lovelace-dev/templates/decluttering-templates.yaml # Changed/Added in 0.12.0
       
# Views
# The following 5 views are swipable, the order
# of these 5 files is the swipe order as well.
# The first view is the page 0. In my setup
# the interface defaults to view 1.
title: Home
background: var(--background-image) # This is the background image that will be used in all the views. (currently backgrounds are set in themes, dont edit this if you want themes to work)
views:
  - !include lovelace-dev/views/climate.yaml
#  - !include lovelace-dev/views/main_view.yaml
#  - !include lovelace-dev/views/lights.yaml
#  - !include lovelace-dev/views/devices.yaml
  - !include lovelace-dev/views/security.yaml
# The views below are used as fake popup cards
# They are non swipable and will behave just like
# a popup card or conditional cards. The order of
# these files will not change anything.
#  - !include lovelace-dev/views/vacuum.yaml
#  - !include lovelace-dev/views/vacuum-zoned-cleaning.yaml
  - !include lovelace-dev/views/alarm.yaml
#  - !include lovelace-dev/views/jimmy.yaml
#  - !include lovelace-dev/views/stephanie.yaml
#  - !include lovelace-dev/views/tala.yaml
#  - !include lovelace-dev/views/scenes.yaml
#  - !include lovelace-dev/views/main_menu.yaml
#  - !include lovelace-dev/views/cleaning.yaml
#  - !include lovelace-dev/views/floorplan.yaml
#  - !include lovelace-dev/views/remote.yaml
#  - !include lovelace-dev/views/links.yaml
#  - !include lovelace-dev/views/calendar.yaml
#  - !include lovelace-dev/views/laundry.yaml
#  - !include lovelace-dev/views/media.yaml
#  - !include lovelace-dev/views/downloads.yaml
#  - !include lovelace-dev/views/energy.yaml
#  - !include lovelace-dev/views/other.yaml
#  - !include lovelace-dev/views/currently_on.yaml
#  - !include lovelace-dev/views/location.yaml
  - !include lovelace-dev/views/themes.yaml
#  - !include lovelace-dev/views/postnl-jimmy.yaml
#  - !include lovelace-dev/views/postnl-stephanie.yaml
#  - !include lovelace-dev/views/weather.yaml
# Note that this order and the way this works might change in the near future.
# It will be the removal of swipe-cards in favor of CCH swipe gestures.