decluttering_templates:
  !include lovelace/decluttering_templates/decluttering_templates.yaml

title: Les Jambons
background: var(--background)
views:
  - !include lovelace/00_home_view.yaml
  - !include lovelace/05_lights_view.yaml
  - !include lovelace/10_media_view.yaml
  - !include lovelace/20_system_graphs.yaml
