homeassistant:
  customize:
    device_tracker.audi_e_tron_50_position:
      entity_picture: "/local/images/audi_e_tron_50_icon.png"
      friendly_name: "Audi e-tron"
      
script:
  audi_lock_etron:
    alias: '[Audi] Lock e-tron'
    sequence: 
      - service: audiconnect.execute_vehicle_action
        data: 
          vin: !secret audi_vin
          action: lock

  audi_start_preheat_etron:
    alias: '[Audi] Start Preheater e-tron'
    sequence: 
      - service: audiconnect.execute_vehicle_action
        data: 
          vin: !secret audi_vin
          action: start_preheater
               
  audi_stop_preheat_etron:
    alias: '[Audi] Stop Preheater e-tron'
    sequence: 
      - service: audiconnect.execute_vehicle_action
        data: 
          vin: !secret audi_vin
          action: stop_preheater
        
automation:
  - id: 0c10e45f-53ce-4324-8ddf-60b036c74b3c
    alias: '[Audi] Send notification when door unlocked at night'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.konnected_alarm
        to: armed_home
    mode: single
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id:
              - binary_sensor.audi_e_tron_50_doors
              - binary_sensor.audi_e_tron_50_doors_lock
              - binary_sensor.audi_e_tron_50_hood
              - binary_sensor.audi_e_tron_50_sun_roof
              - binary_sensor.audi_e_tron_50_trunk
              - binary_sensor.audi_e_tron_50_trunk_lock
              - binary_sensor.audi_e_tron_50_windows
            state: 'off'
      - condition: zone
        entity_id: device_tracker.audi_e_tron_50_position
        zone: zone.home
    action:
      # - service: lock.lock
      #   entity: lock.audi_e_tron_50_door_lock
      - service: notify.mobile_app_sm_g986b
        data_template:
          title: Audi e-tron
          message: Check windows, roof and trunk before falling asleep ;-)
          data:
            channel: Alert
            tag: alert
      # - service: notify.mobile_app_iphone_van_stephanie
      #   data:
      #     title: Trash collection is today
      #     message: Take {{ states('sensor.afvalinfo_today')|replace(' ',' and ') }} outside
      #     data:
      #       push:
      #         thread-id: "alert"
      #         presentation_options:
      #           - alert
      #           - badge

  - id: 40ac7f19-d355-4563-be77-ece38b68ea34
    alias: '[Audi] Send notification when trunk is open'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.audi_e_tron_50_trunk
        to: 'on'
        for: "00:10:00"
    mode: single
    action:
      - service: notify.mobile_app_sm_g986b
        data_template:
          title: Audi e-tron
          message: Trunk is open
          data:
            channel: Alert
            tag: alert
