homeassistant:
  customize:
    switch.backyard_siren:
      friendly_name: Backyard Siren
      icon: mdi:alarm-bell
    switch.living_room_do_not_disturb_switch:
      friendly_name: Living Room Echo Dot
    switch.living_room_fire_tv_stick_do_not_disturb_switch:
      friendly_name: Living Room FireTV Stick
    switch.master_bedroom_do_not_disturb_switch:
      friendly_name: Master Bedroom Echo Dot
    switch.master_bedroom_fire_tv_stick_do_not_disturb_switch:
      friendly_name: Master Bedroom FireTV Stick
    switch.lucas_room_do_not_disturb_switch:
      friendly_name: Lucas' Room Echo Dot
    switch.timo_s_room_do_not_disturb_switch:
      friendly_name: Timo's Room Echo Dot
    switch.emilie_s_room_do_not_disturb_switch:
      friendly_name: Emilie's Room Echo Dot

group:
  alexa:
    - media_player.dennis_s_alexa_app_on_surface_pro_4
    - media_player.dennis_s_alexa_apps
    - media_player.dennis_s_alexa_on_cortana
    - media_player.emilie_s_room
    - media_player.living_room
    - media_player.lucas_room
    - media_player.master_bedroom
    - media_player.this_device
    - media_player.timo_s_room
    - media_player.living_room_fire_tv_stick
    - media_player.master_bedroom_fire_tv_stick

sensor:
  - platform: template
    sensors:
        last_alexa:
          entity_id:
          - media_player.living_room
          - media_player.master_bedroom
          - media_player.lucas_room
          - media_player.timo_s_room
          - media_player.emilie_s_room
          - media_player.living_room_fire_tv_stick
          - media_player.master_bedroom_fire_tv_stick
          value_template: >
            {{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}

binary_sensor:
  - platform: template
    sensors:
      alexa_guard_unavailable:
        friendly_name: "Alexa Guard" 
        device_class: problem
        entity_id:
        - alarm_control_panel.alexa_guard_7514f
        delay_on:
          minutes: 5
        value_template: "{% if not is_state('alarm_control_panel.alexa_guard_7514f', 'unavailable') %} 'off' {% else %} 'on' {% endif %}"

alert:
  alexa_guard_unavailable:
    name: Alexa Guard unavailable
    entity_id: binary_sensor.alexa_guard_unavailable
    state: 'on'
    repeat: 30
    can_acknowledge: false
    skip_first: false
    message: "Check refresh token for Alexa Media Player Custom Component"
    done_message: "Alexa Media Player Custom Component has restored itself" 
    notifiers:
      - mobile_app_sm_g960f
    data:
      tag: 'alexa-guard-unavailable'
