ring:
  username: !secret ring_username
  password: !secret ring_password

life360:
  driving_speed: 30
  interval_seconds: 10
  max_gps_accuracy: 200
  max_update_wait:
    minutes: 45
  warning_threshold: 2
  error_threshold: 3

#alexa_media:
#  accounts:
#    email: !secret amazon_user
#    password: !secret amazon_password
#    url: amazon.com

group:
  alexa:
    - media_player.dennis_s_alexa_app_on_surface_pro_4
    - media_player.dennis_s_alexa_apps
    - media_player.dennis_s_alexa_on_cortana
    - media_player.emilie_s_room_echo_dot
    - media_player.living_room_echo_dot
    - media_player.lucas_room_echo_dot
    - media_player.master_bedroom_echo_dot
    - media_player.this_device
    - media_player.timo_s_room_echo_dot
    - media_player.living_room_fire_tv_stick
    - media_player.master_bedroom_fire_tv_stick

automation:
  - alias: "[Alexa] Enable Do Not Disturb"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: night
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.master_bedroom_echo_dot_do_not_disturb_switch
            - switch.master_bedroom_fire_tv_stick_do_not_disturb_switch
            - switch.lucas_room_echo_dot_do_not_disturb_switch
            - switch.timo_s_room_echo_dot_do_not_disturb_switch
            - switch.emilie_s_room_echo_dot_do_not_disturb_switch

  - alias: "[Alexa] Disable Do Not Disturb"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: morning
    action:
      - service: switch.turn_off
        data:
          entity_id:
            - switch.master_bedroom_echo_dot_do_not_disturb_switch
            - switch.master_bedroom_fire_tv_stick_do_not_disturb_switch
            - switch.lucas_room_echo_dot_do_not_disturb_switch
            - switch.timo_s_room_echo_dot_do_not_disturb_switch
            - switch.emilie_s_room_echo_dot_do_not_disturb_switch

