homeassistant:
  customize:
    device_tracker.smg960f:
      friendly_name: Dennis
    device_tracker.iphone_van_stephanie:
      friendly_name: Stephanie
    device_tracker.iphone_van_lucas:
      friendly_name: Lucas
    device_tracker.oneplus_a5010:
      friendly_name: Timo

device_tracker:
  - platform: bluetooth_tracker
    new_device_defaults:
      track_new_devices: true

  - platform: nmap_tracker
    hosts: 192.168.178.0/24
    home_interval: 3
    new_device_defaults:
    track_new_devices: true

  # - platform: upc_connect
  #   password: !secret upc_connect_password
  #   host: !secret upc_connect_host
    
automation:
  - id: 7321cea0-b530-4d2c-9b88-59eabd8693a6
    alias: '[System] Request Location Update'
    initial_state: 'true'
    trigger:
      - platform: time_pattern
    # This will match every 5 minutes
        minutes: "/5"
    action:
      - service: notify.mobile_app_dennis_galaxy
        data:
          message: "request_location_update"