homeassistant:
  customize:
    device_tracker.sm_g986b:
      friendly_name: Dennis
    device_tracker.iphone_van_stephanie:
      friendly_name: Stephanie
    device_tracker.iphone_van_lucas:
      friendly_name: Lucas
    device_tracker.sm_g781b:
      friendly_name: Timo


