homeassistant:
  customize:
    device_tracker.sm_g986b:
      friendly_name: Dennis
      entity_picture: /local/images/dennis-square.jpg
    device_tracker.iphone_van_stephanie:
      friendly_name: Stephanie
      entity_picture: /local/images/stephanie-square.jpg
    device_tracker.iphone_van_lucas:
      friendly_name: Lucas
      entity_picture: /local/images/lucas-square.jpg
    device_tracker.sm_g781b:
      friendly_name: Timo
      entity_picture: /local/images/timo-square.jpg
    device_tracker.audi_a1_sportback_position:
      friendly_name: Audi A1 Sportback
      entity_picture: /local/images/audi-a1.jpg
      track: false
    device_tracker.audi_e_tron_position:
      friendly_name: Audi e-tron
      entity_picture: /local/images/audi-etron.jpg
      track: false


