homeassistant:
  customize:
    device_tracker.sm_g960f:
      friendly_name: Dennis
    device_tracker.iphone_van_stephanie:
      friendly_name: Stephanie
    device_tracker.iphone_van_lucas:
      friendly_name: Lucas
    device_tracker.oneplus_a5010:
      friendly_name: Timo

device_tracker:
  ## - platform: bluetooth_tracker
  #   new_device_defaults:
  #     track_new_devices: true

  - platform: nmap_tracker
    hosts: 192.168.178.0/24
    home_interval: 3
    new_device_defaults:
    track_new_devices: true
    exclude:
     - 192.168.178.105
