homeassistant:
  customize:
    device_tracker.sm_g960f:
      friendly_name: Dennis
    device_tracker.iphone_van_stephanie:
      friendly_name: Stephanie
    device_tracker.iphone_van_lucas:
      friendly_name: Lucas
    device_tracker.oneplus_a5010:
      friendly_name: Timo

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
    exclude:
     - 192.168.1.10
