nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

automation:
  - id: f1ac429c-e0c6-4859-a3a1-d271136334fa
    alias: '[Alarm] Smoke Detected'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.entryway_nest_protect_smoke_status
        to: emergency
      - platform: state
        entity_id: sensor.hallway_nest_protect_smoke_status
        to: emergency
      - platform: state
        entity_id: sensor.attic_nest_protect_smoke_status
        to: emergency
      - platform: state
        entity_id: sensor.entryway_nest_protect_smoke_status
        to: warning
      - platform: state
        entity_id: sensor.hallway_nest_protect_smoke_status
        to: warning
      - platform: state
        entity_id: sensor.attic_nest_protect_smoke_status
        to: warning
    action:
      - service: cover.open_cover
        data:
          entity_id:
            - cover.master_bedroom_roller_shutter
            - cover.shelly_shsw_25_c4c695
      - service: cover.close_cover
        data:
          entity_id:
            - cover.backyard_awning
      - service: notify.mobile_app_sm_g960f
        data:
          message: Smoke detected
          title: Nest Protect
          data:
            ttl: 0
            priority: high      
            channel: Alarm
            tag: alarm
            sticky: 'true'
            color: 'red'
      - service: notify.mobile_app_iphone_van_stephanie
        data:
          message: Smoke detected
          title: Nest Protect

  - id: a3f8f81e-db50-480b-87a5-146530934099
    alias: '[Alarm] CO Detected'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.entryway_nest_protect_co_status
        to: emergency
      - platform: state
        entity_id: sensor.hallway_nest_protect_co_status
        to: emergency
      - platform: state
        entity_id: sensor.attic_nest_protect_co_status
        to: emergency
      - platform: state
        entity_id: sensor.entryway_nest_protect_co_status
        to: warning
      - platform: state
        entity_id: sensor.hallway_nest_protect_co_status
        to: warning
      - platform: state
        entity_id: sensor.attic_nest_protect_co_status
        to: warning
    action:
      - service: cover.open_cover
        data:
          entity_id:
            - cover.master_bedroom_roller_shutter
            - cover.shelly_shsw_25_c4c695
      - service: cover.close_cover
        data:
          entity_id:
            - cover.backyard_awning
      - service: persistent_notification.create
        data:
          message: CO detected
          title: Nest Protect
      - service: notify.mobile_app_sm_g960f
        data:
          message: CO detected
          title: Nest Protect
          data:
            ttl: 0
            priority: high      
            channel: Alarm
            tag: alarm
            sticky: 'true'
            color: 'red'
      - service: notify.mobile_app_iphone_van_stephanie
        data:
          message: CO detected
          title: Nest Protect
      - service: persistent_notification.create
        data:
          message: CO detected
          title: Nest Protect
