binary_sensor:
  - platform: ping
    host: 8.8.8.8
    name: "Ping Google 1"
  - platform: ping
    host: 8.8.4.4
    name: "Ping Google 2"
  # - platform: template
  #   sensors:
  #     internet_connection:
  #       device_class: connectivity
  #       value_template: >-
  #         {{ is_state('binary_sensor.ping_google_1', 'on')
  #            or is_state('binary_sensor.ping_google_2', 'on') }}
  #       friendly_name: "Internet connection"

template:
  - binary_sensor:
      - name: Internet connection
        unique_id: 3da5e17d-d766-4764-b089-6b8c28b4d897
        device_class: connectivity
        state: >-
          {{ is_state('binary_sensor.ping_google_1', 'on')
             or is_state('binary_sensor.ping_google_2', 'on') }}

automation:
  - id: 21640b6b-8bc9-40e2-ba34-1da182425de0
    alias: Internet is up again
    trigger:
      - platform: state
        entity_id: binary_sensor.internet_connection
        from: "off"
        to: "on"
    action:
        - service: notify.mobile_app_sm_g986b
          data:
            message: Internet is up again
            data:
              channel: Alert
              tag: alert
        - service: notify.mobile_app_iphone_van_stephanie
          data:
            message: Internet is up again
            data:
              push:
                thread-id: "alert"
                presentation_options:
                  - alert
                  - badge
        - service: notify.mobile_app_iphone_van_emilie
          data:
            message: Internet is up again
            data:
              push:
                thread-id: "alert"
                presentation_options:
                  - alert
                  - badge                  