group:
  shelly_firmware_update:
    name: Shelly Firmware Update
    entities:
      - binary_sensor.shelly_1pm_b98825_firmware_update
      - binary_sensor.shelly_1pm_f27a0a_firmware_update
      - binary_sensor.shelly_1pm_f2f9bf_firmware_update
      - binary_sensor.shelly_2_5_c4c695_firmware_update
      - binary_sensor.shelly_2_5_c4c708_firmware_update
      - binary_sensor.shelly_2_5_c4c964_firmware_update
      - binary_sensor.shelly_2_5_40F52023217D_firmware_update
      - binary_sensor.shelly_dimmer_d0f0af_firmware_update
      - binary_sensor.shelly_dimmer_d17712_firmware_update
      - binary_sensor.shelly_dimmer_d17b0e_firmware_update
      - binary_sensor.shelly_dimmer_d47c54_firmware_update
      - binary_sensor.shelly_dimmer_d48409_firmware_update
      - binary_sensor.shelly_plug_s_8013cd_firmware_update
      - binary_sensor.shelly_plug_s_8016cb_firmware_update
      - binary_sensor.shelly_plug_s_f8d1ea_firmware_update
      - binary_sensor.shelly_plug_s_f8d1fa_firmware_update

script:
  shelly_update_firmware:
    alias: '[Shelly] Update Firmware'
    sequence: 
      service: mqtt.publish
      data:
        topic: shellies/command
        payload: update_fw

automation:
  - id: 263db818-00d1-4691-8847-b0bd2d491fbb
    alias: '[Shelly] Shellies Announce'
    trigger:
      - platform: homeassistant
        event: start
    mode: single
    action:
      service: mqtt.publish
      data:
        topic: shellies/command
        payload: announce

  - id: 9d090e06-286a-437d-9e76-810f938782f0
    alias: '[Shelly] Shellies Discovery'
    mode: queued
    max: 999
    trigger:
      platform: mqtt
      topic: shellies/announce
    action:
      service: python_script.shellies_discovery
      data_template:
        id: '{{ trigger.payload_json.id }}'
        mac: '{{ trigger.payload_json.mac }}'
        fw_ver: '{{ trigger.payload_json.fw_ver }}'
        model: '{{ trigger.payload_json.model }}'
        discovery_prefix: 'homeassistant'
        qos: 0
        shellyplug-s-8013CD:
          relay-0: "switch"
          relay-0-name: "Living Room Amplifier"
          force_update_sensors: true
        shellyplug-s-8016CB:
          relay-0: "light"
          relay-0-name: "Lucas Room Floor Lamp"
          force_update_sensors: true
        shellyplug-s-F8D1EA:
          relay-0: "switch"
          relay-0-name: "Attic Washing Machine"
          force_update_sensors: true
        shellyplug-s-F8D1FA:
          relay-0: "switch"
          relay-0-name: "Attic Tumble Dryer"
          force_update_sensors: true
        shellyswitch25-c4c964:
          mode: "roller"
          roller-0-name: "Master Bedroom Roller Shutter"
          force_update_sensors: true
        shellyswitch25-c4c695:
          mode: "roller"
          roller-0-name: "Lucas Room Roller Shutter"
          force_update_sensors: true
        shellyswitch25-c4c708:
          mode: "roller"
          roller-0-name: "Backyard Awning"
          force_update_sensors: true
        shellydimmer-d17b0e:
          light-0-name: "Living Room Dining Table Light"
          force_update_sensors: true
        shellydimmer-D48409:
          light-0-name: "Living Room Wall Lights"
          force_update_sensors: true
        shellydimmer-D17712:
          light-0-name: "Living Room Spot Lights"
          force_update_sensors: true
        shellydimmer-D0F0AF:
          light-0-name: "Living Room Led Strips"
          force_update_sensors: true
        shellydimmer-d47c54:
          light-0-name: "Office Spot Lights"
          force_update_sensors: true
        shelly1pm-F2F9BF:
          relay-0: "light"
          relay-0-name: "Hallway Light"
          push_off_delay: false
          force_update_sensors: true
        shelly1pm-B98825:
          relay-0: "light"
          relay-0-name: "Attic Light"
          push_off_delay: false
          force_update_sensors: true
        shelly1pm-F27A0A:
          relay-0: "light"
          relay-0-name: "Backyard Wall Lights"
          push_off_delay: false
          force_update_sensors: true
        shellyswitch25-40F52023217D:
          mode: "relay"
          relay-0-name: "Master Bedroom Wall Lights"
          relay-1-name: "Master Bedroom Wardrobe Lights"
          push_off_delay: false
          force_update_sensors: true

  - id: 1b3ab5c1-6f54-463c-9c45-827786deb834
    alias: '[Notification] Shelly Firmware updates'
    trigger:
      - platform: state
        entity_id: group.shelly_firmware_update
        to: 'on'
    action:
      service: persistent_notification.create
      data:
        message: "Updates available for Shelly Firmware"
        title: "Shelly Firmware"
        notification_id: shelly