group:
  shelly_firmware:
    name: Shelly Firmware
    entities:
      - cover.shelly_shsw_25_c4c695_firmware_update
      - cover.shelly_shsw_25_c4c708_firmware_update
      - cover.shelly_shsw_25_c4c964_firmware_update
      - light.shelly_shdm_1_d0f0af_firmware_update
      - light.shelly_shdm_1_d17712_firmware_update
      - light.shelly_shdm_1_d17b0e_firmware_update
      - light.shelly_shdm_1_d47c54_firmware_update
      - light.shelly_shdm_1_d48409_firmware_update
      - light.shelly_shplg_s_8016cb_firmware_update
      - light.shelly_shsw_pm_b98825_firmware_update
      - light.shelly_shsw_pm_f27a0a_firmware_update
      - light.shelly_shsw_pm_f2f9bf_firmware_update
      - switch.shelly_shplg_s_8013cd_firmware_update
      - switch.shelly_shplg_s_f8d1ea_firmware_update
      - switch.shelly_shplg_s_f8d1fa_firmware_update

binary_sensor:
  - platform: template
    sensors:
      # True if there's an update available for supervisor
      updater_shelly:
        friendly_name: 'Updater - Shelly'
        device_class: problem
        entity_id:
          - group.shelly_firmware
        value_template: "{{ states('group.shelly_firmware') }}"
        availability_template: "{{ states('group.shelly_firmware') != 'unknown' }}"

alert:
  # Shelly update is available - un-acknowledgeable, auto-dismiss, me only
  shelly_update_available:
    name: Shelly has an update
    entity_id: group.shelly_firmware
    state: 'on'
    can_acknowledge: false
    repeat: 360
    title: 'Update for Shelly available'
    message: "Updates available for Shelly"
    notifiers:
    - 'dennis'
    data:
      tag: 'shelly_update_available'
      url: 'https://my.shelly.cloud/#dashboard'
