homeassistant:
  customize:
    binary_sensor.attic_motion_motion:
      friendly_name: Attic Motion

group:
  shelly_firmware_update:
    name: Shelly Firmware Update
    # Shell Motion, D/W2 and I3 have no firmware update entity
    entities:
      - binary_sensor.attic_light_firmware_update
      - binary_sensor.attic_tumble_dryer_firmware_update
      - binary_sensor.attic_washing_machine_firmware_update
      - binary_sensor.backyard_awning_firmware_update
      - binary_sensor.backyard_garden_light_firmware_update
      - binary_sensor.backyard_wall_light_firmware_update
      - binary_sensor.bathroom_light_firmware_update
      - binary_sensor.dennis_bedside_light_firmware_update
      - binary_sensor.emilie_s_room_light_firmware_update
      - binary_sensor.emilies_room_switch_firmware_update
      - binary_sensor.entryway_light_firmware_update
      - binary_sensor.entryway_wall_light_firmware_update
      - binary_sensor.guestroom_light_firmware_update
      - binary_sensor.hallway_light_firmware_update
      - binary_sensor.kitchen_light_firmware_update
      - binary_sensor.living_room_amplifier_firmware_update
      - binary_sensor.living_room_dining_table_light_firmware_update
      - binary_sensor.living_room_led_strips_firmware_update
      - binary_sensor.living_room_spot_light_firmware_update
      - binary_sensor.living_room_tv_and_painting_li_firmware_update
      - binary_sensor.living_room_wall_light_firmware_update
      - binary_sensor.lucas_room_floor_light_firmware_update
      - binary_sensor.lucas_room_light_firmware_update
      - binary_sensor.lucas_room_roller_shutter_firmware_update
      - binary_sensor.master_bedroom_light_firmware_update
      - binary_sensor.master_bedroom_roller_shutter_firmware_update
      - binary_sensor.office_desk_light_firmware_update
      - binary_sensor.office_led_strip_firmware_update
      - binary_sensor.office_painting_light_firmware_update
      - binary_sensor.office_spot_light_firmware_update
      - binary_sensor.stephanie_s_bedside_light_firmware_update
      - binary_sensor.timo_s_room_light_firmware_update
      - binary_sensor.ziggo_router_firmware_update

automation:
  - alias: "Toggle emilie's room light"
    trigger:
      platform: event
      event_type: shelly.click
      event_data:
        device: shellyix3-E8DB84D2842B
        channel: 1
        click_type: single
    action:
      service: light.toggle
      target:
        entity_id: light.emilie_s_room_light

  - alias: "Turn on emilie's room light at 5%"
    trigger:
      - platform: event
        event_type: shelly.click
        event_data:
          device: shellyix3-E8DB84D2842B
          channel: 1
          click_type: double
    action:
      - service: light.turn_on
        entity_id: light.emilie_s_room_light
        data:
          brightness_pct: 5

  - alias: "Turn on emilie's room light at 100%"
    trigger:
      - platform: event
        event_type: shelly.click
        event_data:
          device: shellyix3-E8DB84D2842B
          channel: 1
          click_type: triple
    action:
      - service: light.turn_on
        entity_id: light.emilie_s_room_light
        data:
          brightness_pct: 100

  - alias: "Turn on emilie's room light at 65%"
    trigger:
      - platform: event
        event_type: shelly.click
        event_data:
          device: shellyix3-E8DB84D2842B
          channel: 1
          click_type: long
    action:
      - service: light.turn_on
        entity_id: light.emilie_s_room_light
        data:
          brightness_pct: 65

  - alias: "Turn on emilie's room light at 30%"
    trigger:
      - platform: event
        event_type: shelly.click
        event_data:
          device: shellyix3-E8DB84D2842B
          channel: 1
          click_type: single_long
    action:
      - service: light.turn_on
        entity_id: light.emilie_s_room_light
        data:
          brightness_pct: 30
    
