homeassistant:
  customize:
    camera.front_door:
      friendly_name: Front Door
    camera.backyard:
      friendly_name: Backyard

automation:
  - id: 6afbd950-7db2-44df-8eb4-d6c46d57f7af
    alias: '[Notification] Low Battery Notification'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.front_door_battery
          - sensor.backyard_battery
        below: 15
      - platform: numeric_state
        entity_id:
          - sensor.front_door_battery
          - sensor.backyard_battery
        below: 10
    mode: single
    action:
      - service: persistent_notification.create
        data_template:
          message: "{{ trigger.to_state.name }} reported low battery, please charge."
          title: Ring Battery Low

  - id: 18bb3b86-f2d8-47d9-908a-b6f1555a15e9
    alias: '[Notification] Play doorbell chime on Echo'
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_ding
        from: 'off'
        to: 'on'
    mode: single
    condition:
      - condition: state
        entity_id: cover.backyard_awning
        state: open
      - condition: template
        value_template: "{{  (as_timestamp(now()) - as_timestamp(states.binary_sensor.backyard_motion.last_changed)) < 1800  }}"
    action:
      - service: media_player.play_media
        data:
          media_content_id: 'amzn_sfx_doorbell_chime_02'
          media_content_type: sound  
          entity_id: media_player.living_room

  - id: 2b0fc466-bcbd-4af1-b1fe-215c2ad2ccbd
    alias: '[Ring] Arm Home Ring Mode based on Konnected Alarm'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.konnected_alarm
        to: armed_away
    mode: single
    action:
      - service: alarm_control_panel.alarm_arm_home
        entity_id:
          - alarm_control_panel.woerden_mode_settings

  - id: e2909fc6-e760-413c-b137-a105ed27b8f6
    alias: '[Ring] Arm Away Ring Mode based on Konnected Alarm'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.konnected_alarm
        to: armed_away
    mode: single
    action:
      - service: alarm_control_panel.alarm_arm_away
        entity_id:
          - alarm_control_panel.woerden_mode_settings
      
  - id: f2f7b8f8-1299-42fb-85ab-2d86e55362a2
    alias: '[Ring] Disarm Ring Mode based on Konnected Alarm'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.konnected_alarm
        to: disarmed
    mode: single
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id:
          - alarm_control_panel.woerden_mode_settings          
