homeassistant:
  customize:
    camera.doorbell:
      friendly_name: Doorbell Camera
    camera.backyard_camera:
      friendly_name: Backyard Camera

automation:
  - id: 6afbd950-7db2-44df-8eb4-d6c46d57f7af
    alias: '[Notification] Ring Low Battery'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.doorbell_battery
          - sensor.backyard_camera_battery
        below: 15
      - platform: numeric_state
        entity_id:
          - sensor.doorbell_battery
          - sensor.backyard_camera_battery
        below: 10
    mode: single
    action:
      - service: persistent_notification.create
        data_template:
          message: "{{ trigger.to_state.name }} reported low battery, please charge."
          title: Ring Battery Low

  - id: 2b0fc466-bcbd-4af1-b1fe-215c2ad2ccbd
    alias: '[Ring] Arm Home Ring Mode based on Konnected Alarm'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.konnected_alarm
        to: armed_home
    mode: single
    action:
      - service: alarm_control_panel.alarm_arm_home
        entity_id:
          - alarm_control_panel.woerden_mode

  - id: e2909fc6-e760-413c-b137-a105ed27b8f6
    alias: '[Ring] Arm Away Ring Mode based on Konnected Alarm'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.konnected_alarm
        to: armed_away
    mode: single
    action:
      - service: alarm_control_panel.alarm_arm_away
        entity_id:
          - alarm_control_panel.woerden_mode
      
  - id: f2f7b8f8-1299-42fb-85ab-2d86e55362a2
    alias: '[Ring] Disarm Ring Mode based on Konnected Alarm'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.konnected_alarm
        to: disarmed
    mode: single
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id:
          - alarm_control_panel.woerden_mode          
