homeassistant:
  customize:
    camera.front_door:
      friendly_name: Front Door
    camera.backyard:
      friendly_name: Backyard

automation:
  - id: 6afbd950-7db2-44df-8eb4-d6c46d57f7af
    alias: '[Notification] Low Battery Notification'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.front_door_battery
          - sensor.backyard_battery
        below: 15
      - platform: numeric_state
        entity_id:
          - sensor.front_door_battery
          - sensor.backyard_battery
        below: 10
    action:
      - service: persistent_notification.create
        data_template:
          message: "{{ trigger.to_state.name }} reported low battery, please charge."
          title: Ring Battery Low

  - id: 18bb3b86-f2d8-47d9-908a-b6f1555a15e9
    alias: '[Notification] Play doorbell chime on Echos'
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_ding
        from: 'off'
        to: 'on'
    condition:
    action:
      - service: media_player.play_media
        data:
          media_content_id: 'amzn_sfx_doorbell_chime_02'
          media_content_type: sound  
        entity_id: 
          - media_player.master_bedroom
          - media_player.lucas_room
          - media_player.timo_s_room
          - media_player.emilie_s_room
