homeassistant:
  customize:
    camera.front_door:
      friendly_name: Last Motion Front Door
    camera.backyard:
      friendly_name: Last Motion Backyard

# binary_sensor:
#   - platform: ring

# sensor:
#   - platform: ring

# camera:
#   - platform: ring

# switch:
#   - platform: ring

camera:
  - platform: generic
    name: Ring Livestream
    stream_source: http://hassio.local:port/public/stream.m3u8
    still_image_url: http://hassio.local:port/public/stream.m3u8

