homeassistant:
  customize:
    camera.front_door:
      friendly_name: Last Motion Front Door
    camera.front_door:
      friendly_name: Last Motion Backyard

binary_sensor:
  - platform: ring

sensor:
  - platform: ring

camera:
  - platform: ring

automation:
  - alias: Motion in backyard
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: binary_sensor.ring_backyard_motion
      to: 'on'
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: alarm_control_panel.Konnected_Alarm
        state: armed_away
      - condition: state
        entity_id: alarm_control_panel.Konnected_Alarm
        state: armed_home
    action:
    - service: homeassistant.turn_on
      entity_id: script.backyardmotion

  - alias: Low Ring Battery Notification
    initial_state: 'on'
    trigger:
    - platform: numeric_state
      entity_id: sensor.ring_front_door_battery
      below: 10
    - platform: numeric_state
      entity_id: sensor.ring_front_door_battery
      below: 5
    #  - platform: numeric_state
    #    entity_id: sensor.ring_backyard_battery
    #    below: 10
    #  - platform: numeric_state
    #    entity_id: sensor.ring_backyard_battery
    #    below: 5
    action:
    - service: persistent_notification.create
      data_template:
        message: "{{ trigger.entity_id }} reported low battery, please charge."
        title: Ring Battery Low
    - service: notify.html5_galaxy_s9
      data_template:
        message: "{{ trigger.entity_id }} reported low battery, please charge."
        title: Ring Battery Low


#  - alias: '[Security] Ring Doorbell Flash Lights'
#    initial_state: 'on'
#    trigger: 
#      - platform: state
#        entity_id: binary_sensor.ring_front_door_ding
#        to: 'on'
#    action:
#      - service: python_script.flash_lights_upstairs_hallway_and_yard

switch:
  - platform: ring

script:
  backyardmotion:
    alias: 'Backyard Motion'
    sequence:
      - service: notify.alexa_media
        data:
          data:
            type: tts
          target:
            - group.alexa
          message: "Motion in the backyard"
      - service: notify.html5
        data:
          title: Ring
          message: There is motion at your backyard
          data:
            actions:
              - action: open
                icon: "/local/icons/konnected.png"
                title: Open Home Assistant
            tag: ring_alert
            ttl: 86400
            priority: high      
      - service: notify.notify
        data:
          message: There is motion at your backyard
          data:
            push:
              badge: 0
              category: ring_alert  