homeassistant:
  customize:
    camera.front_door:
      friendly_name: Last Motion Front Door
    camera.backyard:
      friendly_name: Last Motion Backyard

binary_sensor:
  - platform: ring

sensor:
  - platform: ring

camera:
  - platform: ring

switch:
  - platform: ring

