homeassistant:
  customize:
    switch.siren:
      friendly_name: Alarm Siren
      icon: mdi:alarm-bell
    alarm_control_panel.konnected_alarm:
      friendly_name: Home Alarm
      entity_picture: "/local/icons/konnected.png"
    alarm_control_panel.alexa_guard_7514f:
      friendly_name: Alexa Guard

alarm_control_panel:
  - platform: manual
    name: Konnected Alarm
    pending_time: 60
    delay_time: 20
    trigger_time: 300
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 300
      delay_time: 0
      trigger_time: 300

script:
  konnectedstandby:
    alias: '[Alarm] Konnected Standby'
    sequence:
      - service: alarm_control_panel.alarm_disarm
        entity_id:
          - alarm_control_panel.konnected_alarm
          - alarm_control_panel.alexa_guard_7514f
