homeassistant:
  customize:
    switch.siren:
      friendly_name: Alarm siren
      icon: mdi:alarm-bell
    alarm_control_panel.alexa_guard_7514f:
      friendly_name: Alexa Guard

konnected:
  access_token: !secret konnected_access_token
  devices:
    - id: !secret konnected_device_id
      binary_sensors:
        - zone: 1
          type: motion
          name: 'Entryway'
        - zone: 2
          type: motion
          name: 'Kitchen'
        - zone: 3
          type: motion
          name: 'Living Room'
        - zone: 4
          type: motion
          name: 'Office'
        - zone: 5
          type: motion
          name: 'Garage'
      switches:
        - zone: out
          name: 'Siren'
      blink: false

alarm_control_panel:
  - platform: manual
    name: Konnected Alarm
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 300
      delay_time: 20

script:
  konnectedstandby:
    alias: Alarm - Konnected Standby
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.konnectedstatus
          option: disarmed
      - service: alarm_control_panel.alarm_disarm
        entity_id:
          - alarm_control_panel.konnected_alarm
          - alarm_control_panel.alexa_guard_7514f

sensor:
  - platform: template
    sensors:
      sirens:
        friendly_name: 'Siren sound'
        entity_id: switch.siren, switch.backyard_siren
        value_template: >-
          {% if is_state('switch.siren', 'on') or is_state("switch.siren", "on") %}
            signaling
          {% else %}
            silent
          {% endif %}

input_select:
  konnectedstatus:
    name: Alarm status
    options:
      - disarmed
      - armed_home
      - armed_away
    initial: disarmed
    icon: mdi:security