homeassistant:
  customize:
    switch.siren:
      friendly_name: Alarm Siren
      icon: mdi:alarm-bell
    alarm_control_panel.konnected_alarm:
      friendly_name: Home Alarm

alarm_control_panel:
  - platform: manual
    name: Konnected Alarm

script:
  konnectedstandby:
    alias: '[Alarm] Konnected Standby'
    sequence:
      - service: alarm_control_panel.alarm_disarm
        entity_id:
          - alarm_control_panel.konnected_alarm
      - service: switch.turn_off
        entity_id: 
          - switch.siren
          - switch.backyard_camera_siren

automation:
  - id: 3c28420d-2670-4215-bd93-7b2ca445fbb4
    alias: '[Alarm] Arm Konnected'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: group.household
        from: home
        to: not_home
    mode: single
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: not
        conditions:
          - condition: state
            entity_id: alarm_control_panel.konnected_alarm
            state: armed_away
    action:
      - service: alarm_control_panel.alarm_arm_away
        entity_id:
          - alarm_control_panel.konnected_alarm
      - service: notify.alexa_media
        data:
          data:
            type: announce
          target:
          - group.alexa
          message: I'll start guarding now

  - id: f586bfa3-cec3-4881-8cbb-bb2ceb9aea62
    alias: '[Alarm] Deactivate siren'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.konnected_alarm
        to: disarmed
    mode: single
    condition:
          - condition: state
            entity_id: input_boolean.guest_mode
            state: 'off'
          - condition: or
            conditions:
              - condition: state
                entity_id: switch.siren
                state: 'on'
              - condition: state
                entity_id: switch.backyard_camera_siren
                state: 'on'
    action:
      - service: switch.turn_off
        entity_id:
          - switch.siren
          - switch.backyard_camera_siren

  # - id: 2d57cc0c-7317-486f-a2f2-b755c59ac660
  #   alias: '[Alarm] Disarm Konnected at night'
  #   initial_state: 'true'
  #   trigger:
  #     - platform: zone
  #       entity_id:
  #         - person.dennis
  #         - person.stephanie
  #         - person.lucas
  #         - person.timo
  #       zone: zone.home
  #       event: enter
  #   mode: single
  #   condition:
  #     - condition: state
  #       entity_id: alarm_control_panel.konnected_alarm
  #       state: armed_home
  #     - condition: state
  #       entity_id: input_boolean.guest_mode
  #       state: 'off'
  #   action:
  #     - service: script.turn_on
  #       entity_id: script.konnectedstandby

  # - id: d4ce8893-a219-499b-bd45-18a2bc5bc6c2
  #   alias: '[Alarm] Disarm Konnected from Away'
  #   initial_state: 'true'
  #   trigger:
  #     - platform: state
  #       entity_id: group.household
  #       from: not_home
  #       to: home
  #   mode: single
  #   condition:
  #     - condition: or
  #       conditions:
  #         - condition: state
  #           entity_id: alarm_control_panel.konnected_alarm
  #           state: armed_away
  #         - condition: state
  #           entity_id: alarm_control_panel.konnected_alarm
  #           state: pending
  #     - condition: state
  #       entity_id: input_boolean.guest_mode
  #       state: 'off'
  #   action:
  #     - service: script.turn_on
  #       entity_id: script.konnectedstandby

  - id: 1b827364-51fb-4f38-b4e2-860eb9bfcd9c
    alias: '[Alarm] Disarm Konnected when arriving home'
    initial_state: 'true'
    trigger:
      - platform: zone
        entity_id:
          - person.dennis
          - person.stephanie
          - person.lucas
          - person.timo
        zone: zone.home
        event: enter
    mode: single
    action:
      - service: script.turn_on
        entity_id: script.konnectedstandby

  - id: b937f244-4e93-4ab7-9310-a1c77a7c05d4
    alias: '[Alarm] Disarm Konnected in the morning'
    initial_state: 'true'
    trigger:
      - platform: time
        at: 06:00:00
    mode: single
    condition:
      - condition: state
        entity_id: group.household
        state: home
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.konnectedstandby

  - id: 8efa2a7d-23c9-4bb3-b163-4e1bf820976d
    alias: '[Alarm] Konnected Standby'
    initial_state: 'true'
    trigger:
      - platform: time_pattern
        minutes: /10
        seconds: 0
    mode: single
    condition:
      - condition: state
        entity_id: group.household
        state: home
      - condition: time
        after: 06:15:00
        before: '21:00:00'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: or
        conditions:
        - condition: state
          entity_id: alarm_control_panel.konnected_alarm
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.konnected_alarm
          state: armed_away
    action:
      - service: script.turn_on
        entity_id: script.konnectedstandby

  - id: 72a6ac29-9e75-4f47-a22b-407609b26ee9
    alias: '[Alarm] Konnected Log Activation when armed away'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.front_door_door
          - binary_sensor.living_room_door_door
          - binary_sensor.office_door_door
          - binary_sensor.garage_door_door
          - binary_sensor.kitchen_window_door
          - binary_sensor.bathroom_window_door
          - binary_sensor.timo_s_room_window_door
          - binary_sensor.guestroom_window_door
          - binary_sensor.entryway_motion
          - binary_sensor.kitchen_motion
          - binary_sensor.living_room_motion
          - binary_sensor.office_motion
          - binary_sensor.garage_motion
          - binary_sensor.attic_motion_motion
          - binary_sensor.backyard_camera_motion
        to: 'on'
    mode: single
    condition:
      - condition: state
        entity_id: alarm_control_panel.konnected_alarm
        state: armed_away
    action:
      - service: logbook.log
        data_template:
          name: "Alarm activated: "
          message: >-
            {{ trigger.entity_id }}

  - id: f8f69cdb-1c35-497b-b80b-5c4e31a376b1
    alias: '[Alarm] Konnected Log Activation when armed home'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.front_door_door
          - binary_sensor.living_room_door_door
          - binary_sensor.office_door_door
          - binary_sensor.garage_door_door
          - binary_sensor.kitchen_window_door
          - binary_sensor.bathroom_window_door
          - binary_sensor.timo_s_room_window_door
          - binary_sensor.guestroom_window_door
          - binary_sensor.backyard_camera_motion
        to: 'on'
    mode: single
    condition:
      - condition: state
        entity_id: alarm_control_panel.konnected_alarm
        state: armed_home
    action:
      - service: logbook.log
        data_template:
          name: "Alarm activated: "
          message: >-
            {{ trigger.entity_id }}

  - id: 0c082214-fab9-4833-9efc-7f220b337811
    alias: '[Alarm] Trigger Alarm'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.konnected_alarm
        to: triggered
    mode: single
    action:
      - service: switch.turn_on
        entity_id: switch.siren
      - service: switch.turn_on
        entity_id: switch.backyard_camera_siren
      # - service: scene.turn_on
      #   entity_id: scene.emergency
      - service: notify.alexa_media
        data:
          data:
            type: announce
          target:
            - group.alexa
          message: The alarm was activated
      - service: notify.android_devices
        data:
          title: "Alarm was activated"
          message: "Motion detected which triggered the alarm"
          data:
            ttl: 0
            priority: high
            channel: Critical
      - service: notify.iphone_devices
        data:
          title: "Alarm was activated"
          message: "Motion detected which triggered the alarm"
          data:
            push:
              sound:
                name: default
                critical: 1
                volume: 1.0                  

  - id: 583df5d2-69c7-49e2-93a2-0c49d936b0fb
    alias: '[Alarm] Pending alarm when armed away'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id:
          - group.motion_sensor
          - group.door_window_sensor
        to: 'on'
    mode: single
    condition:
      - condition: state
        entity_id: alarm_control_panel.konnected_alarm
        state:
          - armed_away
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.konnected_alarm
      - service: notify.alexa_media
        data:
          data:
            type: announce
          target:
            - group.alexa
          message: Motion detected, the alarm will activate shortly. Motion detected, the alarm will activate shortly.

  - id: b5839c86-095b-4edf-8129-143a72681e7b
    alias: '[Alarm] Pending alarm when armed home'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id:
          - group.door_window_sensor
        to: 'on'
    mode: single
    condition:
      - condition: state
        entity_id: alarm_control_panel.konnected_alarm
        state:
          - armed_home
      - condition: state
        entity_id: person.timo
        state: "not_home"    
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.konnected_alarm
      - service: notify.alexa_media
        data:
          data:
            type: announce
          target:
            - group.alexa
          message: Motion detected, the alarm will activate shortly. Motion detected, the alarm will activate shortly.

  - id: 759236b8-533d-4b4e-b474-636903a87f5f
    alias: '[Alarm] Pending alarm when armed home (Timo home)'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id:
          - group.door_window_sensor_except_timo_s_room
        to: 'on'
    mode: single
    condition:
      - condition: state
        entity_id: alarm_control_panel.konnected_alarm
        state:
          - armed_home
      - condition: state
        entity_id: person.timo
        state: "home"    
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.konnected_alarm
      - service: notify.alexa_media
        data:
          data:
            type: announce
          target:
            - group.alexa
          message: Motion detected, the alarm will activate shortly. Motion detected, the alarm will activate shortly.


  - id: 2ae00756-b4a9-4068-acc8-c574a8a60fd4
    alias: '[Motion] Motion in backyard at night'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: binary_sensor.backyard_camera_motion
        to: 'on'
    mode: single
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.konnected_alarm
          state: armed_away
        - condition: state
          entity_id: alarm_control_panel.konnected_alarm
          state: armed_home
        - condition: time
          after: '00:00:00'
          before: '07:00:00'
    action:
      - service: notify.alexa_media
        data:
          data:
            type: announce
          target:
            - group.alexa
          message: "Motion in the backyard"
      - service: notify.all_devices
        data:
          title: Ring
          message: There is motion at your backyard
          data:
            tag: motion
            channel: Motion
            clickAction: '/lovelace/camera'
            push:
              thread-id: "motion"

  - id: d28bb847-8061-473b-b632-7a7d684cee78
    alias: '[Alarm] Turn on lights with an emergency'
    trigger:
      - platform: state
        entity_id:
          - sensor.entryway_nest_protect_smoke_status
          - sensor.hallway_nest_protect_smoke_status
          - sensor.attic_nest_protect_smoke_status
          - sensor.entryway_nest_protect_co_status
          - sensor.hallway_nest_protect_co_status
          - sensor.attic_nest_protect_co_status
        to: emergency
    mode: single
    action:
      - service: scene.turn_on
        entity_id: scene.emergency
