automation:
  - id: 811e963d-f24e-47bd-b0fb-b519bb0e6dbb
    alias: '[Climate] Away Mode'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: group.household
        from: home
        to: not_home
    mode: single
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
    action:
      - service: climate.set_preset_mode
        entity_id: climate.living_room
        data:
          preset_mode: eco

  - id: 039d5bb6-5335-4c0c-9c37-c0d286bcecae
    alias: '[Climate] Home Mode'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: group.household
        from: not_home
        to: home
    mode: single
    action:
      - service: climate.set_preset_mode
        entity_id: climate.living_room
        data:
          preset_mode: none