homeassistant:
  customize:
    cover.master_bedroom_roller_shutter_level:
      friendly_name: Master Bedroom Roller Shutter
    cover.lucas_room_roller_shutter_level:
      friendly_name: Lucas Room Roller Shutter
    cover.backyard_sunscreen:
      friendly_name: Backyard Sunscreen
    sensor.lucas_room_roller_shutter_power:
      friendly_name: Lucas Room Roller Shutter Power  
    sensor.master_bedroom_roller_shutter_power:
      friendly_name: Master Bedroom Roller Shutter Power

cover:
  - platform: group
    name: 'Roller Shutters'
    entities:
      - cover.master_bedroom_roller_shutter_level  
      - cover.lucas_room_roller_shutter_level

script:
  alexa_open_the_cover:
    alias: '[Alexa] Open the cover'
    sequence:
      - service: cover.open_cover
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "master_bedroom" -%}
              cover.master_bedroom_roller_shutter_level
            {%- elif room == "lucas_room" -%}
              cover.lucas_room_roller_shutter_level
            {%- endif -%}

  alexa_close_the_cover:
    alias: '[Alexa] Close the cover'
    sequence:
      - service: cover.close_cover
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "master_bedroom" -%}
              cover.master_bedroom_roller_shutter_level
            {%- elif room == "lucas_room" -%}
              cover.lucas_room_roller_shutter_level
            {%- endif -%}

  alexa_close_the_cover_with_ventilation:
    alias: '[Alexa] Close the cover with ventilation'
    sequence:
      - service: cover.set_cover_position
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "master_bedroom" -%}
              cover.master_bedroom_roller_shutter_level
            {%- elif room == "lucas_room" -%}
              cover.lucas_room_roller_shutter_level
            {%- endif -%}  
          position: 10