homeassistant:
  customize:
    cover.master_bedroom_roller_shutter_level:
      friendly_name: Master Bedroom Roller Shutter
    cover.lucas_room_roller_shutter_level:
      friendly_name: Lucas Room Roller Shutter
    cover.backyard_sunscreen:
      friendly_name: Backyard Sunscreen
    sensor.lucas_room_roller_shutter_power:
      friendly_name: Lucas Room Roller Shutter Power  
    sensor.master_bedroom_roller_shutter_power:
      friendly_name: Master Bedroom Roller Shutter Power

cover:
  - platform: group
    name: 'Roller Shutters'
    entities:
      - cover.master_bedroom_roller_shutter_level  
      - cover.lucas_room_roller_shutter_level

automation:
  - id: f22881d0-2a37-46f6-86fa-0feaac19de59
    alias: '[Covers] Open in the morning in Master Bedroom'
    initial_state: 'true'
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: group.household
        state: 'home'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
    trigger:
      - platform: time
        at: "08:30:00"
    action:
      - service: cover.open_cover
        data:
          entity_id: cover.master_bedroom_roller_shutter_level

  - id: 2c0fabaa-793e-4d83-a6f6-488b799384e7
    alias: '[Covers] Open in the morning in Lucas Room'
    initial_state: 'true'
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: group.household
        state: 'home'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
    trigger:
      - platform: time
        at: "09:00:00"
    action:
      - service: cover.open_cover
        data:
          entity_id: cover.lucas_room_roller_shutter_level

  - id: 9168307a-6555-489d-b686-643216ff76e9
    alias: '[Covers] Open in the morning during the weekends and holidays'
    initial_state: 'true'
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: group.household
        state: 'home'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'off'
    trigger:
      - platform: time
        at: "11:00:00"
    action:
      - service: cover.open_cover
        data:
          entity_id:
            - cover.master_bedroom_roller_shutter_level
            - cover.lucas_room_roller_shutter_level

  - id: 58a2e68e-7adf-4d08-93d1-a4dd43faeb12
    alias: '[Covers] Close in the evening'
    initial_state: 'true'
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: group.household
        state: 'home'
    trigger:
      - platform: sun
        event: sunset
    action:
      - service: cover.set_cover_position
        data:
          entity_id:
            - cover.master_bedroom_roller_shutter_level
            - cover.lucas_room_roller_shutter_level
          position: 10

  - id: 36999f33-8fcb-423e-972d-425b4efca279
    alias: '[Covers] Close with strong winds'
    initial_state: 'true'
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: below_horizon
    trigger:
      - platform: numeric_state
        entity_id: sensor.br_wind_force
        above: 4
    action:
      - service: cover.close_cover
        data:
          entity_id:
            - cover.master_bedroom_roller_shutter_level
            - cover.lucas_room_roller_shutter_level

  - id: d3a773bf-fc19-4f77-8ad7-00097a2a8bfa
    alias: '[Covers] Open when arriving at daytime'
    initial_state: 'true'
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.br_temperature
        below: 25
      - condition: state
        entity_id: sun.sun
        state: above_horizon
      - condition: template
        value_template: "{%- if states.automation.covers_close_when_leaving.attributes.last_triggered\
          \ -%}\n  {{ (as_timestamp(now()) - as_timestamp(states.automation.covers_close_when_leaving.attributes.last_triggered))\
          \ > 240 }}\n{%- else -%}\n  true\n{%- endif -%}\n"
    trigger:
      - platform: state
        entity_id: group.household
        from: home
        to: not_home
    action:
      - service: cover.open_cover
        data:
          entity_id:
            - cover.master_bedroom_roller_shutter_level
            - cover.lucas_room_roller_shutter_level

  - id: 9c7f65fd-fc67-47e1-a81d-e02afcacdc3e
    alias: '[Covers] Open when arriving at night'
    initial_state: 'true'
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.br_temperature
        below: 25
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - condition: template
        value_template: "{%- if states.automation.covers_close_when_leaving.attributes.last_triggered\
          \ -%}\n  {{ (as_timestamp(now()) - as_timestamp(states.automation.covers_close_when_leaving.attributes.last_triggered))\
          \ > 240 }}\n{%- else -%}\n  true\n{%- endif -%}\n"
    trigger:
      - platform: state
        entity_id: group.household
        from: not_home
        to: home
    action:
      - service: cover.set_cover_position
        data:
          entity_id:
            - cover.master_bedroom_roller_shutter_level
            - cover.lucas_room_roller_shutter_level
          position: 10

  - id: 153b5394-3dde-4ebd-8e3f-4d2bb43e8529
    alias: '[Covers] Close when leaving'
    initial_state: 'true'
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: template
        value_template: "{%- if states.automation.covers_open_when_arriving_1.attributes.last_triggered\
          \ -%}\n  {{ (as_timestamp(now()) - as_timestamp(states.automation.covers_open_when_arriving_1.attributes.last_triggered))\
          \ > 240 }}\n{%- else -%}\n  true\n{%- endif -%}\n"
      - condition: template
        value_template: "{%- if states.automation.covers_open_when_arriving_2.attributes.last_triggered\
          \ -%}\n  {{ (as_timestamp(now()) - as_timestamp(states.automation.covers_open_when_arriving_2.attributes.last_triggered))\
          \ > 240 }}\n{%- else -%}\n  true\n{%- endif -%}\n"
    trigger:
      - platform: state
        entity_id: group.household
        from: home
        to: not_home
      - platform: numeric_state
        entity_id: sensor.br_temperature
        above: 25
    action:
      - service: cover.close_cover
        data:
          entity_id:
            - cover.master_bedroom_roller_shutter_level
            - cover.lucas_room_roller_shutter_level

  - id: c209375b-d473-4d56-8f02-41c3146eae35
    alias: '[Covers] Open when smoke or CO detected'
    initial_state: 'true'
    condition:
    trigger:
      - platform: state
        entity_id: sensor.entryway_nest_protect_smoke_status
        from: 'ok'
      - platform: state
        entity_id: sensor.entryway_nest_protect_co_status
        from: 'ok'
      - platform: state
        entity_id: sensor.hallway_nest_protect_smoke_status
        from: 'ok'
      - platform: state
        entity_id: sensor.hallway_nest_protect_co_status
        from: 'ok'
      - platform: state
        entity_id: sensor.attic_nest_protect_smoke_status
        from: 'ok'
      - platform: state
        entity_id: sensor.attic_nest_protect_co_status
        from: 'ok'
    action:
      - service: cover.open_cover
        data:
          entity_id:
            - cover.master_bedroom_roller_shutter_level
            - cover.lucas_room_roller_shutter_level

script:
  alexa_open_the_cover:
    alias: '[Alexa] Open the cover'
    sequence:
      - service: cover.open_cover
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "master_bedroom" -%}
              cover.master_bedroom_roller_shutter_level
            {%- elif room == "lucas_room" -%}
              cover.lucas_room_roller_shutter_level
            {%- endif -%}

  alexa_close_the_cover:
    alias: '[Alexa] Close the cover'
    sequence:
      - service: cover.close_cover
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "master_bedroom" -%}
              cover.master_bedroom_roller_shutter_level
            {%- elif room == "lucas_room" -%}
              cover.lucas_room_roller_shutter_level
            {%- endif -%}

  alexa_close_the_cover_with_ventilation:
    alias: '[Alexa] Close the cover with ventilation'
    sequence:
      - service: cover.set_cover_position
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "master_bedroom" -%}
              cover.master_bedroom_roller_shutter_level
            {%- elif room == "lucas_room" -%}
              cover.lucas_room_roller_shutter_level
            {%- endif -%}  
          position: 10

  alexa_open_the_cover_halfway:
    alias: '[Alexa] Open the cover halfway'
    sequence:
      - service: cover.set_cover_position
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "master_bedroom" -%}
              cover.master_bedroom_roller_shutter_level
            {%- elif room == "lucas_room" -%}
              cover.lucas_room_roller_shutter_level
            {%- endif -%}  
          position: 60