homeassistant:
  customize:
    cover.master_bedroom_roller_shutter_level:
      friendly_name: Master Bedroom Roller Shutter
    cover.lucas_room_roller_shutter_level:
      friendly_name: Lucas Room Roller Shutter
    cover.backyard_sunscreen:
      friendly_name: Backyard Sunscreen
    sensor.lucas_room_roller_shutter_power:
      friendly_name: Lucas Room Roller Shutter Power  
    sensor.master_bedroom_roller_shutter_power:
      friendly_name: Master Bedroom Roller Shutter Power

cover:
  - platform: group
    name: 'Roller Shutters'
    entities:
      - cover.master_bedroom_roller_shutter_level  
      - cover.lucas_room_roller_shutter_level

