cover:
  - platform: group
    name: 'Roller Shutters'
    entities:
      - cover.master_bedroom_roller_shutter  
      - cover.lucas_room_roller_shutter

script:
  # alexa_open_the_cover:
  #   alias: '[Alexa] Open the cover'
  #   sequence:
  #     - service: cover.open_cover
  #       data_template:
  #         entity_id: >-
  #           {# Use the name of each Echo to determine which room the command likely came from. #}
  #           {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

  #           {%- if room == "master_bedroom" -%}
  #             cover.master_bedroom_roller_shutter
  #           {%- elif room == "lucas_room" -%}
  #             cover.lucas_room_roller_shutter
  #           {%- elif room == "living_room" -%}
  #             cover.backyard_awning
  #           {%- endif -%}

  # alexa_close_the_cover:
  #   alias: '[Alexa] Close the cover'
  #   sequence:
  #     - service: cover.close_cover
  #       data_template:
  #         entity_id: >-
  #           {# Use the name of each Echo to determine which room the command likely came from. #}
  #           {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

  #           {%- if room == "master_bedroom" -%}
  #             cover.master_bedroom_roller_shutter
  #           {%- elif room == "lucas_room" -%}
  #             cover.lucas_room_roller_shutter
  #           {%- elif room == "living_room" -%}
  #             cover.backyard_awning
  #           {%- endif -%}

  # alexa_close_the_cover_with_ventilation:
  #   alias: '[Alexa] Close the cover with ventilation'
  #   sequence:
  #     - service: cover.set_cover_position
  #       data_template:
  #         entity_id: >-
  #           {# Use the name of each Echo to determine which room the command likely came from. #}
  #           {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

  #           {%- if room == "master_bedroom" -%}
  #             cover.master_bedroom_roller_shutter
  #           {%- elif room == "lucas_room" -%}
  #             cover.lucas_room_roller_shutter
  #           {%- endif -%}  
  #         position: 10

  # alexa_open_the_cover_halfway:
  #   alias: '[Alexa] Open the cover halfway'
  #   sequence:
  #     - service: cover.set_cover_position
  #       data_template:
  #         entity_id: >-
  #           {# Use the name of each Echo to determine which room the command likely came from. #}
  #           {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

  #           {%- if room == "master_bedroom" -%}
  #             cover.master_bedroom_roller_shutter
  #           {%- elif room == "lucas_room" -%}
  #             cover.lucas_room_roller_shutter
  #           {%- elif room == "living_room" -%}
  #             cover.backyard_awning
  #           {%- endif -%}  
  #         position: 60

automation:
  - id: f22881d0-2a37-46f6-86fa-0feaac19de59
    alias: '[Cover] Open Master Bedroom roller shutter in the morning'
    initial_state: 'true'
    trigger:
      - platform: time
        at: "08:30:00"
    mode: single
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: group.household
        state: 'home'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
    action:
      - service: cover.open_cover
        data:
          entity_id: cover.master_bedroom_roller_shutter

  - id: 2c0fabaa-793e-4d83-a6f6-488b799384e7
    alias: '[Cover] Open Lucas Room roller shutter in the morning'
    trigger:
      - platform: time
        at: "09:00:00"
    mode: single
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: group.household
        state: 'home'
      - condition: state
        entity_id: person.lucas
        state: 'not_home'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
    action:
      - service: cover.open_cover
        entity_id: cover.lucas_room_roller_shutter

  - id: 28db0c07-c36a-48cd-8d5c-ddda6b91f169
    alias: '[Cover] Open Lucas Room roller shutter when he leaves'
    trigger:
      - platform: state
        entity_id: person.lucas
        from: 'home'
        to: 'not_home'
    mode: single
    condition:
      condition: or
      conditions:
        - condition: "{{ state_attr('cover.lucas_room_roller_shutter', 'current_position') < 100 }}"
        - condition: state
          entity_id: person.dennis
          state: 'home'
        - condition: state
          entity_id: person.stephanie
          state: 'home'
        - condition: state
          entity_id: person.timo
          state: 'home'
        # - condition: state
        #   entity_id: person.emilie
        #   state: 'home'
    action:
      - service: cover.open_cover
        entity_id: cover.lucas_room_roller_shutter

  - id: 9168307a-6555-489d-b686-643216ff76e9
    alias: '[Cover] Open roller shutters in the morning during the weekends and holidays'
    initial_state: 'true'
    trigger:
      - platform: time
        at: "11:00:00"
    mode: single
    condition:
      - condition: state
        entity_id:
          - input_boolean.guest_mode
          - binary_sensor.workday_sensor
        state: 'off'
      - condition: state
        entity_id: group.household
        state: 'home'
    action:
      - service: cover.open_cover
        entity_id:
          - cover.master_bedroom_roller_shutter
          - cover.lucas_room_roller_shutter

  - id: 58a2e68e-7adf-4d08-93d1-a4dd43faeb12
    alias: '[Cover] Close roller shutters in the evening'
    initial_state: 'true'
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        below: 0.0
    mode: single
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: group.household
        state: 'home'
    action:
      - service: cover.set_cover_position
        data:
          entity_id:
            - cover.master_bedroom_roller_shutter
            - cover.lucas_room_roller_shutter
          position: 10

  - id: 36999f33-8fcb-423e-972d-425b4efca279
    alias: '[Cover] Close roller shutters with strong winds'
    initial_state: 'true'
    trigger:
      - platform: numeric_state
        entity_id: sensor.br_wind_speed
        above: 35 #km/h
    mode: single
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") < 0 }}'
    action:
      - service: cover.close_cover
        data:
          entity_id:
            - cover.master_bedroom_roller_shutter
            - cover.lucas_room_roller_shutter

  - id: d3a773bf-fc19-4f77-8ad7-00097a2a8bfa
    alias: '[Cover] Open roller shutters when arriving at daytime'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: group.household
        from: not_home
        to: home
    mode: single
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.br_temperature
        below: 25
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") > 0 }}'
    action:
      - service: cover.open_cover
        data:
          entity_id:
            - cover.master_bedroom_roller_shutter
            - cover.lucas_room_roller_shutter

  - id: 9c7f65fd-fc67-47e1-a81d-e02afcacdc3e
    alias: '[Cover] Open roller shutters when arriving at night'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: group.household
        from: not_home
        to: home
    mode: single
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.br_temperature
        below: 25
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") < 0 }}'
    action:
      - service: cover.set_cover_position
        data:
          entity_id:
            - cover.master_bedroom_roller_shutter
            - cover.lucas_room_roller_shutter
          position: 10

  - id: 153b5394-3dde-4ebd-8e3f-4d2bb43e8529
    alias: '[Cover] Close covers when leaving'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: group.household
        from: home
        to: not_home
    mode: single
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
    action:
      - service: cover.close_cover
        data:
          entity_id:
            - cover.master_bedroom_roller_shutter
            - cover.lucas_room_roller_shutter
            - cover.backyard_awning

  - id: 6c9a2404-5bd8-43e4-beb2-c38afd7d21c5
    alias: '[Cover] Close roller shutters when high temperature'
    initial_state: 'true'
    trigger:
      - platform: numeric_state
        entity_id: sensor.br_temperature
        above: 25
    mode: single
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: group.household
        state: 'home'        
    action:
      - service: cover.close_cover
        data:
          entity_id:
            - cover.master_bedroom_roller_shutter
            - cover.lucas_room_roller_shutter

  - id: 8f5ef152-5503-4e7a-97cf-3e8884f07572
    alias: '[Cover] Open roller shutters when temperature gets cooler'
    initial_state: 'true'
    trigger:
      - platform: numeric_state
        entity_id: sensor.br_temperature
        below: 25
    mode: single
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") > 0 }}'
      - condition: state
        entity_id: group.household
        state: 'home'
      - condition: not
        conditions:
          - condition: state
            entity_id:
              - alarm_control_panel.konnected_alarm
            state: armed_home
    action:
      - service: cover.open_cover
        data:
          entity_id:
            - cover.master_bedroom_roller_shutter
            - cover.lucas_room_roller_shutter

  - id: 94389708-c03d-43f9-9731-ec93ed511526
    alias: '[Cover] Close awning when expected heavy wind or rain'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: sensor.br_precipitation_forecast_total
        from: '0.0'
      - platform: numeric_state
        entity_id: sensor.br_wind_speed
        above: 35 #km/h
    mode: single
    condition:
      - condition: state
        entity_id: cover.backyard_awning
        state: open
    action:
      - service: cover.close_cover
        data:
          entity_id:
            - cover.backyard_awning

  - id: d030ba6f-ee63-4ee6-9cea-a43751aba57b
    alias: '[Cover] Close awning when no motion at night'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: binary_sensor.backyard_camera_motion
        from: "on"
        to: "off"
        for: "00:30:00"
    mode: single
    condition:
      - condition: state
        entity_id: cover.backyard_awning
        state: open
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") < 0 }}'
    action:
      - service: cover.close_cover
        data:
          entity_id:
            - cover.backyard_awning

  - id: 480cedf5-81f6-4321-a83b-f91981fe41e6
    alias: '[Cover] Closed awning'
    initial_state: 'true'
    trigger:
      - platform: time_pattern
        minutes: /5
        seconds: 0
    mode: single
    condition:
      - condition: state
        entity_id: cover.backyard_awning
        state: open
      - condition: or
        conditions:
          - condition: not
            conditions:
              - condition: state
                entity_id: sensor.br_precipitation_forecast_total
                state: '0.0'
          - condition: numeric_state
            entity_id: sensor.br_wind_speed
            above: 35 #km/h
    action:
      - service: cover.close_cover
        data:
          entity_id:
            - cover.backyard_awning
