homeassistant:
  customize:
    input_boolean.dennis_mode:
      templates:
        icon: >
          if (state === 'on') return 'mdi:account';
          else if (state === 'off') return 'mdi:account-off';
        icon_color: >
          if (state === 'on') return 'rgb(56, 150, 56)';
          else if (state === 'off') return 'rgb(249, 251, 255)';

input_boolean:
  dennis_mode:
    name: Dennis Mode
    initial: 'off'
    icon: mdi:account

automation:
  - alias: '[House] Dennis Mode Ask'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: person.dennis
        to: 'Just arrived'
      - platform: state
        entity_id: person.stephanie
        to: 'Just Left'
    condition:
      condition: and
      conditions:
        - condition: or
          conditions:
            - condition: state
              entity_id: person.dennis
              state: 'Home'
            - condition: state
              entity_id: person.dennis
              state: 'Just arrived'
        - condition: or
          conditions:
            - condition: state
              entity_id: person.stephanie
              state: 'Away'
            - condition: state
              entity_id: person.stephanie
              state: 'Just left'
    action:
      - service: notify.html5_galaxy_s9
        data:
          title: 'Home alone!'
          message: 'Turn on mode?'
          data:
            push:
              category: "dennis_mode"

  - alias: '[House] Dennis Mode On'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: HOME_ALONE_MODE_ON
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.dennis_mode
      # - More to come when confirmed working as intended

  - alias: '[House] Dennis Mode Off'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: person.stephanie
        to: 'Just arrived'
      - platform: state
        entity_id: person.stephanie
        to: 'Home'
      - platform: state
        entity_id: person.dennis
        to: 'Just Left'
    condition:
      - condition: state
        entity_id: input_boolean.dennis_mode
        state: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.dennis_mode
      - service: notify.html5_galaxy_s9
        data:
          title: 'No more alone time'
          message: 'Stephanie is home'
      # - service: script.sonos_say
      #   data:
      #     sonos_entity: media_player.living_room_sonos
      #     volume: 0.2
      #     message: 'Stephanie Just arrived'
      #     delay: '00:00:10'

  - alias: '[TTS] Sonos Stephanie Leaving Golf Course'
    initial_state: 'on'
    trigger:
      - platform: zone
        entity_id: person.stephanie
        zone: zone.golf
        event: leave
    action:
      - delay: '00:01:00'
      - condition: state
        entity_id: media_player.living_room_movie_system
        state: 'off'
      - service: script.sonos_say
        data:
          sonos_entity: media_player.living_room_sonos
          volume: 0.2
          message: 'Stephanie is now leaving the golf course'
          delay: '00:00:15'