homeassistant:
  customize:
    binary_sensor.front_door_door:
      friendly_name: Front Door
      device_class: door
    binary_sensor.living_room_door_door:
      friendly_name: Living Room Door
      device_class: door
    binary_sensor.office_door_door:
      friendly_name: Office Door
      device_class: door
    binary_sensor.garage_door_door:
      friendly_name: Garage Door
      device_class: door
    binary_sensor.kitchen_window_door:
      friendly_name: Kitchen Window
      device_class: window
    binary_sensor.bathroom_window_door:
      friendly_name: Bathroom Window
      device_class: window
    binary_sensor.timo_s_room_window_door:
      friendly_name: Timo's Room Window
      device_class: window
    binary_sensor.guestroom_window_door:
      friendly_name: Guestroom Window
      device_class: window

group:
  door_window_sensor:
    name: Door Window Sensor
    # when adding a door window sensor don't forget to update automation id 72a6ac29-9e75-4f47-a22b-407609b26ee9
    entities:
      - binary_sensor.front_door_door
      - binary_sensor.living_room_door_door
      - binary_sensor.office_door_door
      - binary_sensor.garage_door_door
      - binary_sensor.kitchen_window_door
      - binary_sensor.bathroom_window_door
      - binary_sensor.timo_s_room_window_door
      - binary_sensor.guestroom_window_door

  door_window_sensor_except_timo_s_room:
    name: Door Window Sensor
    # when adding a door window sensor don't forget to update automation id 72a6ac29-9e75-4f47-a22b-407609b26ee9
    entities:
      - binary_sensor.front_door_door
      - binary_sensor.living_room_door_door
      - binary_sensor.office_door_door
      - binary_sensor.garage_door_door
      - binary_sensor.kitchen_window_door
      - binary_sensor.bathroom_window_door
      - binary_sensor.guestroom_window_door

binary_sensor:
  - platform: threshold
    name: Front Door Battery
    entity_id: sensor.front_door_battery
    lower: 10
  - platform: threshold
    name: Garage Door Battery
    entity_id: sensor.garage_door_battery
    lower: 10
  - platform: threshold
    name: Living Room Door Battery
    entity_id: sensor.living_room_door_battery
    lower: 10
  - platform: threshold
    name: Office Door Battery
    entity_id: sensor.office_door_battery
    lower: 10
  - platform: threshold
    name: Kitchen Window Battery
    entity_id: sensor.kitchen_window_battery
    lower: 10
  - platform: threshold
    name: Bathroom Window Battery
    entity_id: sensor.bathroom_window_battery
    lower: 10
  - platform: threshold
    name: Timo's Room Window Battery
    entity_id: sensor.timo_s_room_window_battery
    lower: 10
  - platform: threshold
    name: Guestroom Window Battery
    entity_id: sensor.guestroom_window_battery
    lower: 10
  - platform: template
    sensors:
      battery_operated_sensor_unavailable:
        value_template: "{{ is_state('binary_sensor.front_door_door', 'unavailable')
                            or is_state('binary_sensor.garage_door_door', 'unavailable')
                            or is_state('binary_sensor.living_room_door_door', 'unavailable')
                            or is_state('binary_sensor.office_door_door', 'unavailable')
                            or is_state('binary_sensor.bathroom_window_door', 'unavailable')
                            or is_state('binary_sensor.guestroom_window_door', 'unavailable')
                            or is_state('binary_sensor.kitchen_window_door', 'unavailable')
                            or is_state('binary_sensor.timo_s_room_window_door', 'unavailable')
                            or is_state('binary_sensor.kitchen_flood_sensor_flood', 'unavailable')
                            or is_state('binary_sensor.laundry_room_flood_sensor_flood', 'unavailable')
                            or is_state('binary_sensor.attic_motion_motion', 'unavailable') }}"
        friendly_name: "Battery operated sensor is unavailable"

alert:
  # Front Door Battery is low - un-acknowledgeable, auto-dismiss, me only
  front_door_battery_low:
    name: Front Door Sensor Battery Low
    entity_id: binary_sensor.front_door_battery
    state: 'on'
    can_acknowledge: false
    repeat: 360
    title: 'Front Door Sensor Battery low'
    message: "Front Door Sensor Battery is at {{ states('sensor.front_door_battery') }}%. Replace it soon"
    notifiers:
    - mobile_app_sm_g986b
    data:
      tag: 'front_door_battery_low'

  # Garage Door Battery is low - un-acknowledgeable, auto-dismiss, me only
  garage_door_battery_low:
    name: Garage Door Sensor Battery Low
    entity_id: binary_sensor.garage_door_battery
    state: 'on'
    can_acknowledge: false
    repeat: 360
    title: 'Garage Door Sensor Battery low'
    message: "Garage Door Sensor Battery is at {{ states('sensor.garage_door_battery') }}%. Replace it soon"
    notifiers:
    - mobile_app_sm_g986b
    data:
      tag: 'garage_door_battery_low'

  living_room_door_battery_low:
    name: Living Room Door Sensor Battery Low
    entity_id: binary_sensor.living_room_door_battery
    state: 'on'
    can_acknowledge: false
    repeat: 360
    title: 'living Room Door Sensor Battery low'
    message: "Living Room Door Sensor Battery is at {{ states('sensor.living_room_door_battery') }}%. Replace it soon"
    notifiers:
    - mobile_app_sm_g986b
    data:
      tag: 'living_room_door_battery_low'

  office_door_battery_low:
    name: Office Door Sensor Battery Low
    entity_id: binary_sensor.office_door_battery
    state: 'on'
    can_acknowledge: false
    repeat: 360
    title: 'Office Door Sensor Battery low'
    message: "Office Door Sensor Battery is at {{ states('sensor.office_door_battery') }}%. Replace it soon"
    notifiers:
    - mobile_app_sm_g986b
    data:
      tag: 'office_door_battery_low'

  kitchen_window_battery_low:
    name: Kitchen Window Sensor Battery Low
    entity_id: binary_sensor.kitchen_window_battery
    state: 'on'
    can_acknowledge: false
    repeat: 360
    title: 'Kitchen Window Sensor Battery low'
    message: "Kitchen Window Sensor Battery is at {{ states('sensor.kitchen_window_battery') }}%. Replace it soon"
    notifiers:
    - mobile_app_sm_g986b
    data:
      tag: 'kitchen_window_battery_low'

  bathroom_window_battery_low:
    name: Bathroom Window Sensor Battery Low
    entity_id: binary_sensor.bathroom_window_battery
    state: 'on'
    can_acknowledge: false
    repeat: 360
    title: 'Bathroom Window Sensor Battery low'
    message: "Bathroom Window Sensor Battery is at {{ states('sensor.bathroom_window_battery') }}%. Replace it soon"
    notifiers:
    - mobile_app_sm_g986b
    data:
      tag: 'bathroom_window_battery_low'

  timo_s_room_window_battery_low:
    name: Timo's Room Window Sensor Battery Low
    entity_id: binary_sensor.timo_s_room_window_battery
    state: 'on'
    can_acknowledge: false
    repeat: 360
    title: "Timo's Room Window Sensor Battery low"
    message: "Timo's Room Window Sensor Battery is at {{ states('sensor.timo_s_room_window_battery') }}%. Replace it soon"
    notifiers:
    - mobile_app_sm_g986b
    data:
      tag: 'timo_s_room_window_battery_low'

  guestroom_window_battery_low:
    name: Guestroom Window Sensor Battery Low
    entity_id: binary_sensor.guestroom_window_battery
    state: 'on'
    can_acknowledge: false
    repeat: 360
    title: 'Guestroom Window Sensor Battery low'
    message: "Guestroom Window Sensor Battery is at {{ states('sensor.guestroom_window_battery') }}%. Replace it soon"
    notifiers:
    - mobile_app_sm_g986b
    data:
      tag: 'guestroom_window_battery_low'

  # Battery Operated Sensor Unavailable - un-acknowledgeable, auto-dismiss, me only
  battery_operated_sensor_unavailable:
    name: Battery Operated Sensor Unavailable
    entity_id: binary_sensor.battery_operated_sensor_unavailable
    state: 'on'
    can_acknowledge: false
    repeat: 360
    title: 'Battery Operated Sensor Unavailable'
    message: "A door/window or flood sensor is unavailable. Please check."
    notifiers:
    - mobile_app_sm_g986b
    data:
      tag: 'battery_operated_sensor_unavailable'


automation:
  - id: 54601140-994f-4a24-b5f2-3cfeb4d1464d
    alias: '[Door] Front door 10 min open alert'
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_door
        to: 'on'
        for: '00:10:00'
    mode: single
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: group.household
            state: 'home'
          - condition: state
            entity_id: input_boolean.guest_mode
            state: 'on'
    action:
      - service: notify.alexa_media
        data:
          data:
            type: announce
          target:
            - group.alexa
          message: 'The front door is still open, please close it'

  - id: 44b7412b-bfc1-4191-a555-08bc20ed36a1
    alias: '[Door] Garage door 10 min open alert'
    trigger:
      - platform: state
        entity_id: binary_sensor.garage_door_door
        to: 'on'
        for: '00:10:00'
    mode: single
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: group.household
            state: 'home'
          - condition: state
            entity_id: input_boolean.guest_mode
            state: 'on'
    action:
      - service: notify.alexa_media
        data:
          data:
            type: announce
          target:
            - group.alexa
          message: 'The garage door is still open, please close it'

  - id: b10c980b-02a0-4446-8e11-635cd275b3b0
    alias: '[Door] Garage door open alert'
    trigger:
      - platform: state
        entity_id: binary_sensor.garage_door_door
        to: 'on'
    mode: single
    action:
      - service: notify.alexa_media
        data:
          data:
            type: announce
          target:
            - group.alexa
          message: 'The garage door was just opened'

  - id: be5daf0c-c5d5-4d86-a7b3-011b157b110e
    alias: '[Door] Door or window open when leaving home'
    trigger:
      - platform: state
        entity_id: group.household
        from: 'home'
        to: 'not_home'
    condition:
      - condition: state
        entity_id:
          - binary_sensor.front_door_door
          - binary_sensor.living_room_door_door
          - binary_sensor.office_door_door
          - binary_sensor.garage_door_door
          - binary_sensor.kitchen_window_door
          - binary_sensor.bathroom_window_door
          - binary_sensor.timo_s_room_window_door
          - binary_sensor.guestroom_window_door
        state: 'on'
    action:     
      - service: notify.android_devices
        data:
          title: "Door/window open"
          message: "A door or window is still open and nobody at home"
          data:
            ttl: 0
            priority: high
            channel: Critical
      - service: notify.iphone_devices
        data:
          title: "Door/window open"
          message: "A door or window is still open and nobody at home"
          data:
            push:
              sound:
                name: default
                critical: 1
                volume: 1.0            

  - id: 79d59cf7-48ae-42ba-9608-a51af146ad3d
    alias: '[Door] Door or window open when alarm set to armed home'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.konnected_alarm
        to: armed_home
    condition:
      - condition: state
        entity_id:
          - binary_sensor.front_door_door
          - binary_sensor.living_room_door_door
          - binary_sensor.office_door_door
          - binary_sensor.garage_door_door
          - binary_sensor.kitchen_window_door
          - binary_sensor.bathroom_window_door
          - binary_sensor.timo_s_room_window_door
          - binary_sensor.guestroom_window_door
        state: 'on'
    action:     
      - service: notify.android_devices
        data:
          title: "Door/window open"
          message: "A door or window is still open, please check"
          data:
            ttl: 0
            priority: high
            channel: Critical
      - service: notify.iphone_devices
        data:
          title: "Door/window open"
          message: "A door or window is still open, please check"
          data:
            push:
              sound:
                name: default
                critical: 1
                volume: 1.0            
