binary_sensor:
  # True if there's updates available for any HACS components, Addons or the Host
  - platform: threshold
    name: Kitchen Flood Sensor Battery
    entity_id: sensor.kitchen_flood_sensor_battery
    lower: 10
  - platform: threshold
    name: Laundry Flood Sensor Battery
    entity_id: sensor.laundry_room_flood_sensor_battery
    lower: 10

alert:
  # Kitchen Sensor Battery is low - un-acknowledgeable, auto-dismiss, me only
  kitchen_flood_sensor_battery_low:
    name: Kitchen Sensor Battery Low
    entity_id: sensor.kitchen_flood_sensor_battery
    state: 'on'
    can_acknowledge: false
    repeat: 360
    title: 'Kitchen Sensor Battery low'
    message: "Kitchen Sensor Battery is at {{ states('sensor.kitchen_flood_sensor_battery') }}%. Replace it soon"
    notifiers:
    - mobile_app_sm_g986b
    data:
      tag: 'kitchen_sensor_battery'

  # Laundry Room Flood Sensor Battery is low - un-acknowledgeable, auto-dismiss, me only
  laundry_room_flood_sensor_battery_low:
    name: Laundry Room Flood Sensor Battery Low
    entity_id: sensor.laundry_room_flood_sensor_battery
    state: 'on'
    can_acknowledge: false
    repeat: 360
    title: 'Laundry Room Flood Sensor Battery low'
    message: "Laundry Room Flood Sensor Battery is at {{ states('sensor.laundry_room_flood_sensor_battery') }}%. Replace it soon"
    notifiers:
    - mobile_app_sm_g986b
    data:
      tag: 'laundry_room_flood_sensor_battery'

automation:
  - id: 2fc93218-afe8-4a97-8f72-d9e901a9209b
    alias: '[Flood] Flood alert'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.kitchen_flood_sensor_flood
          - binary_sensor.laundry_room_flood_sensor_flood
        to: 'on'
    mode: single
    action:
      - service: notify.alexa_media
        data:
          data:
            type: announce
          target:
            - group.alexa
          message: >
            {% if trigger.entity_id ==  "binary_sensor.kitchen_flood_sensor_flood" %}
              Water leakage under the kitchen sink, check ASAP! I repeat: Water leakage under the kitchen sink, check ASAP! I repeat:
            {% elif trigger.entity_id ==  "binary_sensor.laundry_room_flood_sensor_flood" %}
              Water leakage near the washing machine, check ASAP! I repeat: Water leakage near the washing machine, check ASAP!
            {% endif %}          
      - service: notify.android_devices
        data:
          title: "ALERT: Flood"
          message: >
            {% if trigger.entity_id ==  "binary_sensor.kitchen_flood_sensor_flood" %}
              Water leakage under the kitchen sink, check ASAP! 
            {% elif trigger.entity_id ==  "binary_sensor.laundry_room_flood_sensor_flood" %}
              Water leakage near the washing machine, check ASAP!
            {% endif %}          
          data:
            ttl: 0
            priority: high
            channel: Critical
      - service: notify.iphone_devices
        data:
          title: "ALERT: Flood"
          message: >
            {% if trigger.entity_id ==  "binary_sensor.kitchen_flood_sensor_flood" %}
              Water leakage under the kitchen sink, check ASAP! 
            {% elif trigger.entity_id ==  "binary_sensor.laundry_room_flood_sensor_flood" %}
              Water leakage near the washing machine, check ASAP!
            {% endif %}          
          data:
            push:
              sound:
                name: default
                critical: 1
                volume: 1.0                  
  
      