alert:
  guest_mode:
    name: Guest Mode is on
    entity_id: input_boolean.guest_mode
    state: 'on'
    repeat: 360
    can_acknowledge: true
    skip_first: false
    done_message: Guest mode is off
    notifiers:
      - mobile_app_sm_g986b
      - mobile_app_iphone_van_stephanie
    data:
      tag: 'guest-mode-on'

automation:
  - id: c93f7aa4-2fd8-4088-88b3-8f07226a7fc5
    alias: '[House] Turn on Rise and Shine scene in the morning'
    trigger:
      - platform: state
        entity_id: binary_sensor.entryway_motion
        from: 'off'
        to: 'on'
    mode: single
    condition:
      - condition: numeric_state
        entity_id: sensor.entryway_motion_trigger_count
        below: 1
      - condition: time
        after: '06:00:00'
        before: '10:00:00'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
    action:
      - service: scene.turn_on
        entity_id: scene.rise_and_shine