homeassistant:
  customize:
    light.living_room_spot_lights_dimmer_level:
      friendly_name: Living Room Spot Lights
    light.office_spot_lights_dimmer_level:
      friendly_name: Office Spot Lights