homeassistant:
  customize:
    light.shelly_shdm_1_d17712:
      friendly_name: Living Room Spot Lights
    light.shelly_shdm_1_d48409:
      friendly_name: Living Room Wall Lights
    light.shelly_shdm_1_d17b0e:
      friendly_name: Living Room Dining Table Light       
    light.shelly_shdm_1_d47c54:
      friendly_name: Office Spot Lights
    sensor.living_room_spot_dimmer_power:
        friendly_name: Living Room Spot Lights
    sensor.living_room_wall_dimmer_power:
      friendly_name: Living Room Wall Lights
    sensor.living_room_dining_table_dimmer_power:
      friendly_name: Living Room Dining Table Light       
    sensor.office_spot_dimmer_power:
        friendly_name: Office Spot Lights

script:
  alexa_turn_on_light:
    alias: '[Alexa] Turn on Light'
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "master_bedroom" -%}
              light.master_bedroom_roller_shutter_level
            {%- elif room == "timo_s_room" -%}
              light.timo_s_room_desk_light
            {%- endif -%}

  alexa_turn_off_light:
    alias: '[Alexa] Turn off Light'
    sequence:
      - service: light.turn_off
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "master_bedroom" -%}
              light.master_bedroom_roller_shutter_level
            {%- elif room == "timo_s_room" -%}
              light.timo_s_room_desk_light
            {%- endif -%}
