homeassistant:
  customize:
    light.living_room_spot_lights_dimmer_level:
      friendly_name: Living Room Spots
    light.living_room_table_light_dimmer_level:
      friendly_name: Dining Table Light       
    light.office_spot_lights_dimmer_level:
      friendly_name: Office Spots
