homeassistant:
  customize:
    light.living_room_spot_lights:
      friendly_name: Living Room Spot Lights
    light.living_room_wall_lights:
      friendly_name: Living Room Wall Lights
    light.living_room_dining_table_light:
      friendly_name: Living Room Dining Table Light       
    light.office_spot_lights:
      friendly_name: Office Spot Lights
    sensor.living_room_spot_dimmer_power:
        friendly_name: Living Room Spot Lights
    sensor.living_room_wall_dimmer_power:
      friendly_name: Living Room Wall Lights
    sensor.living_room_dining_table_dimmer_power:
      friendly_name: Living Room Dining Table Light       
    sensor.office_spot_dimmer_power:
        friendly_name: Office Spot Lights

light:
  - platform: group
    name: living_room
    entities:
      - light.living_room_dining_table_light
      - light.living_room_wall_lights
      - light.living_room_spot_lights
      - light.living_room_led_strips
      - light.office_spot_lights
  - platform: group
    name: master_bedroom
    entities:
      - light.master_bedroom_wardrobe_lights
      - light.master_bedroom_wall_lights
  - platform: group
    name: Lucas_room
    entities:
      - light.lucas_room_floor_lamp

script:
  blink_light:
    alias: '[Light] Blink lights'
    sequence:
      repeat:
        count: 10
        sequence:
        - service: light.toggle
          entity_id:
            - light.living_room_dining_table_light
            - light.hallway_light
            - light.attic_light
        - delay:
            milliseconds: 500

  light_turn_on_light:
    alias: '[Light] Turn on light'
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "living_room" -%}
              light.living_room
            {%- elif room == "master_bedroom" -%}
              light.master_bedroom
            {%- elif room == "lucas_room" -%}
              light.lucas_room
            {%- endif -%}

  light_turn_off_light:
    alias: '[Light] Turn off light'
    sequence:
      - service: light.turn_off
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "living_room" -%}
              light.living_room
            {%- elif room == "master_bedroom" -%}
              light.master_bedroom
            {%- elif room == "lucas_room" -%}
              light.lucas_room
            {%- endif -%}

  light_turn_on_floor_lamp:
    alias: '[Light] Turn on floor lamp'
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "lucas_room" -%}
              light.lucas_room_floor_lamp
            {%- endif -%}

  light_turn_off_floor_lamp:
    alias: '[Light] Turn off floor lamp'
    sequence:
      - service: light.turn_off
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "lucas_room" -%}
              light.lucas_room_floor_lamp
            {%- endif -%}

  light_turn_on_wall_light:
    alias: '[Light] Turn on wall light'
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "master_bedroom" -%}
              light.master_bedroom_wall_lights
            {%- endif -%}

  light_turn_off_wall_light:
    alias: '[Light] Turn off wall light'
    sequence:
      - service: light.turn_off
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "master_bedroom" -%}
              light.master_bedroom_wall_lights
            {%- endif -%}

  light_turn_on_wardrobe_light:
    alias: '[Light] Turn on wardrobe light'
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "master_bedroom" -%}
              light.master_bedroom_wardrobe_lights
            {%- endif -%}

  light_turn_off_wardrobe_light:
    alias: '[Light] Turn off wardrobe light'
    sequence:
      - service: light.turn_off
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "master_bedroom" -%}
              light.master_bedroom_wardrobe_lights
            {%- endif -%}
                      

automation:
  - id: e4519647-e24b-4f1b-8682-51aaa8ce4576
    alias: '[Lights] Turn on lights when arriving home at night'
    trigger:
      - platform: state
        entity_id: group.household
        from: not_home
        to: home
    mode: single
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") < 0 }}'
    action:
      - service: scene.turn_on
        entity_id: scene.dinner_time  

  - id: 11e9f0f4a-99b9-427c-85f7-b703a564a511
    alias: '[Lights] Turn off hallway and attic light after 10 minutes'
    trigger:
      - platform: state
        entity_id:
          - light.entryway_light
          - light.hallway_light
          - light.attic_light
        to: 'on'
        for: "00:10:00"
    mode: single
    action:
      service: light.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"

  - id: d558b383-921e-4740-bafd-9a888b45fa9a
    alias: '[Lights] Turn on backyard lights when dark outside'
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        below: 0.0
    mode: single
    condition:
      - condition: time
        after: '16:00:00'
        before: '23:59:59'
    action:
      service: light.turn_on
      entity_id:
        - light.backyard_wall_lights
      # data_template:
      #   entity_id: >
      #     {% if is_state("cover.backyard_awning", "closed") %}
      #       light.backyard_wall_lights
      #     {% else %}
      #       light.backyard_wall_lights, light.backyard_garden_lights
      #     {% endif %}

  - id: 1802426d-6f61-4dde-ab2c-5cd3b5233243
    alias: '[Lights] Turn off backyard lights at midnight'
    trigger:
      platform: time
      at: "23:59:59"
    mode: single
    action:
      service: light.turn_off
      entity_id:
        - light.backyard_wall_lights
        # - light.backyard_garden_lights

  - id: 0f21c88f-c82e-459d-81c5-c5cf170e6279
    alias: '[Lights] Turn on backyard lights when motion'
    trigger:
      - platform: state
        entity_id: binary_sensor.backyard_motion
        to: 'on'
    mode: single
    condition:
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") < 0 }}'
      - condition: time
        after: '00:00:00'
        before: '08:30:00'
    action:
      service: light.turn_on
      entity_id:
        - light.backyard_wall_lights
        # - light.backyard_garden_lights

  - id: 5199be8b-2458-44b0-bd98-6bda33cd96f0
    alias: '[Lights] Turn off backyard lights when no motion'
    trigger:
      - platform: state
        entity_id: binary_sensor.backyard_motion
        to: 'off'
        for: "00:10:00"
    mode: single
    condition:
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") < 0 }}'
      - condition: time
        after: '00:00:00'
        before: '08:30:00'
    action:
      service: light.turn_off
      entity_id:
        - light.backyard_wall_lights
        # - light.backyard_garden_lights

  - id: 9c912ebd-f7a5-46f5-9215-187dda6e2630
    alias: '[Lights] Turn off Lucas Room Floor Lamp'
    trigger:
      - platform: time_pattern
        minutes: "/10"
    mode: single
    condition:
      - condition: state
        entity_id: person.lucas
        state: not_home
      - condition: state
        entity_id: light.lucas_room_floor_lamp
        state: 'on'
    action:
      service: light.turn_off
      entity_id:
        - light.lucas_room_floor_lamp
      
    