homeassistant:
  customize:
    light.shelly_shdm_1_d17712:
      friendly_name: Living Room Spot Lights
    light.shelly_shdm_1_d48409:
      friendly_name: Living Room Wall Lights
    light.shelly_shdm_1_d17b0e:
      friendly_name: Living Room Dining Table Light       
    light.shelly_shdm_1_d47c54:
      friendly_name: Office Spot Lights
    sensor.living_room_spot_dimmer_power:
        friendly_name: Living Room Spot Lights
    sensor.living_room_wall_dimmer_power:
      friendly_name: Living Room Wall Lights
    sensor.living_room_dining_table_dimmer_power:
      friendly_name: Living Room Dining Table Light       
    sensor.office_spot_dimmer_power:
        friendly_name: Office Spot Lights

automation:
  - id: e4519647-e24b-4f1b-8682-51aaa8ce4576
    alias: '[Lights] Turn on lights when arriving home at night'
    trigger:
      - platform: state
        entity_id: group.household
        from: not_home
        to: home
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") < 0 }}'
    action:
      - service: scene.turn_on
        entity_id: scene.dinner_time  

  - id: 11e9f0f4a-99b9-427c-85f7-b703a564a511
    alias: '[Lights] Turn off hallway and attic light after 10 minutes'
    trigger:
      - platform: state
        entity_id:
          - light.entryway_light
          - light.shelly_shsw_pm_f2f9bf
          - light.shelly_shsw_pm_b98825
        to: 'on'
        for: "00:10:00"
    action:
      service: light.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"

  - id: d558b383-921e-4740-bafd-9a888b45fa9a
    alias: '[Lights] Turn on backyard lights when dark outside'
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        below: 0.0
    condition:
      - condition: time
        after: '16:30:00'
        before: '00:00:00'
    action:
      service: light.turn_on
      data_template:
        entity_id: >
          {% if (as_timestamp(now()) - as_timestamp(states.binary_sensor.backyard_motion.last_changed)) > 1800 %}
            light.shelly_shsw_pm_f27a0a
          {% else %}
            light.shelly_shsw_pm_f27a0a, light.shelly_shplg_s_8016cb
          {% endif %}

  - id: 0e58a3aa-8e64-4b24-bdba-b32dd6a68322
    alias: '[Lights] Turn off backyard garden lights after 30 minutes no motion'
    trigger:
      - platform: state
        entity_id: binary_sensor.backyard_motion
        from: "on"
        to: "off"
        for: "00:30:00"
    condition:
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") < 0 }}'
      - condition: time
        after: '16:30:00'
        before: '00:00:00'
    action:
      service: light.turn_off
      entity_id:
        - light.shelly_shplg_s_8016cb

  - id: 1802426d-6f61-4dde-ab2c-5cd3b5233243
    alias: '[Lights] Turn off backyard lights at midnight'
    trigger:
      platform: time
      at: "00:00:00"
    action:
      service: light.turn_off
      entity_id:
        - light.shelly_shsw_pm_f27a0a
        - light.shelly_shplg_s_8016cb

  - id: 0f21c88f-c82e-459d-81c5-c5cf170e6279
    alias: '[Lights] Turn on backyard lights when motion'
    trigger:
      - platform: state
        entity_id: binary_sensor.backyard_motion
        to: 'on'
    condition:
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") < 0 }}'
      - condition: time
        after: '00:00:01'
        before: '08:30:00'
    action:
      service: light.turn_on
      entity_id:
        - light.shelly_shsw_pm_f27a0a
        - light.shelly_shplg_s_8016cb

  - id: 5199be8b-2458-44b0-bd98-6bda33cd96f0
    alias: '[Lights] Turn off backyard lights when no motion'
    trigger:
      - platform: state
        entity_id: binary_sensor.backyard_motion
        to: 'off'
        for: "00:10:00"
    condition:
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") < 0 }}'
      - condition: time
        after: '00:00:01'
        before: '08:30:00'
    action:
      service: light.turn_off
      entity_id:
        - light.shelly_shsw_pm_f27a0a
        - light.shelly_shplg_s_8016cb

