homeassistant:
  customize:
    light.living_room_spot_dimmer_level:
      friendly_name: Living Room Spot Lights
    light.living_room_wall_dimmer_level:
      friendly_name: Living Room Wall Lights
    light.living_room_dining_table_dimmer_level:
      friendly_name: Living Room Dining Table Light       
    light.office_spot_dimmer_level:
      friendly_name: Office Spot Lights
    sensor.living_room_spot_dimmer_power:
        friendly_name: Living Room Spot Lights Power
    sensor.living_room_wall_dimmer_power:
      friendly_name: Living Room Wall Lights Power
    sensor.living_room_dining_table_dimmer_power:
      friendly_name: Living Room Dining Table Light Power       
    sensor.office_spot_dimmer_power:
        friendly_name: Office Spot Lights Power
    sensor.backyard_light_current_consumption:
        friendly_name: Backyard Lights Power
    sensor.backyard_light_total_consumption_attr:
        friendly_name: Backyard Lights Total Consumption

light:
  - platform: group
    name: 'Inside lights'
    entities:
      - light.living_room_spot_dimmer_level
      - light.living_room_wall_dimmer_level
      - light.living_room_dining_table_dimmer_level  
      - light.office_spot_dimmer_level

  - platform: group
    name: 'Downstairs lights'
    entities:
      - light.living_room_spot_dimmer_level  
      - light.office_spot_dimmer_level
      - light.living_room_wall_dimmer_level
      - light.living_room_dining_table_dimmer_level  
      - light.entryway

  - platform: group
    name: 'Upstairs lights'
    entities:
      - light.hallway_light
      
  - platform: group
    name: 'Outdoor lights'
    entities:
      - light.backyard_light

script:
  alexa_turn_on_the_light:
    alias: '[Light] Turn on the light'
    sequence:
      - service: homeassistant.turn_on
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "living_room" -%}
              light.downstairs_lights
            {%- elif room == "master_bedroom" -%}
              light.master_bedroom
            {%- elif room == "lucas_room" -%}
              light.lucas_room
            {%- elif room == "timo_s_room" -%}
              light.timo_room
            {%- elif room == "emilie_s_room" -%}
              light.emilie_room
            {%- endif -%}

  alexa_turn_off_the_light:
    alias: '[Light] Turn off the light'
    sequence:
      - service: homeassistant.turn_on
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "living_room" -%}
              light.downstairs_lights
            {%- elif room == "master_bedroom" -%}
              light.master_bedroom
            {%- elif room == "lucas_room" -%}
              light.lucas_room
            {%- elif room == "timo_s_room" -%}
              light.timo_s_room
            {%- elif room == "emilie_s_room" -%}
              light.emilie_s_room
            {%- endif -%}

automation:
  - id: 9664f92b-26b9-4cc0-a422-4a03382a86a1
    alias: '[Lights] Turn off all lights when away'
    trigger:
      - platform: state
        entity_id: group.household
        from: home
        to: not_home
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
    action:
      - service: homeassistant.turn_off
        entity_id: light.inside_lights

  - id: e4519647-e24b-4f1b-8682-51aaa8ce4576
    alias: '[Lights] Turn on lights when arriving home at night'
    trigger:
      - platform: state
        entity_id: group.household
        from: not_home
        to: home
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: below_horizon
    action:
      - service: light.turn_on
        data:
          entity_id: light.living_room_dining_table_dimmer_level
          brightness: 95
      - service: light.turn_on
        data:
          entity_id: light.living_room_wall_dimmer_level
          brightness: 108

  - id: d558b383-921e-4740-bafd-9a888b45fa9a
    alias: '[Lights] Turn on backyard lights when dark outside'
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      below: -4.0
    condition:
    action:
      service: light.turn_on
      entity_id: light.backyard_light

  - id: 1802426d-6f61-4dde-ab2c-5cd3b5233243
    alias: '[Lights] Turn off backyard lights at midnight'
    trigger:
      platform: time
      at: "00:00:00"
    condition:
    action:
      service: light.turn_off
      entity_id: light.backyard_light

  - id: 0f21c88f-c82e-459d-81c5-c5cf170e6279
    alias: '[Lights] Turn on backyard lights when motion'
    trigger:
      - platform: state
        entity_id: binary_sensor.backyard_motion
        to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        below: -4.0
      - condition: time
        after: '00:00:00'
        before: '12:00:00'
    action:
      service: light.turn_on
      entity_id: light.backyard_light

  - id: 5199be8b-2458-44b0-bd98-6bda33cd96f0
    alias: '[Lights] Turn off backyard lights when no motion'
    trigger:
      - platform: state
        entity_id: binary_sensor.backyard_motion
        to: 'off'
        for: "00:10:00"
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        below: -4.0
      - condition: time
        after: '00:00:00'
        before: '12:00:00'
    action:
      service: light.turn_off
      entity_id: light.backyard_light
