homeassistant:
  customize:
    light.living_room_spot_lights_dimmer_level:
      friendly_name: Living Room Spot Lights
    light.living_room_table_light_dimmer_level:
      friendly_name: Living Room Table Light       
    light.office_spot_lights_dimmer_level:
      friendly_name: Office Spot Lights
    sensor.living_room_spot_lights_dimmer_power:
        friendly_name: Living Room Spot Lights Power
    sensor.living_room_spot_lights_dimmer_power:
        friendly_name: Office Spot Lights Power

