homeassistant:
  customize:
    light.living_room_spot_dimmer_level:
      friendly_name: Living Room Spot Lights
    light.living_room_wall_dimmer_level:
      friendly_name: Living Room Wall Lights
    light.living_room_dining_table_dimmer_level:
      friendly_name: Living Room Dining Table Light       
    light.office_spot_dimmer_level:
      friendly_name: Office Spot Lights
    sensor.living_room_spot_dimmer_power:
        friendly_name: Living Room Spot Lights Power
    sensor.living_room_wall_dimmer_power:
      friendly_name: Living Room Wall Lights Power
    sensor.living_room_dining_table_dimmer_power:
      friendly_name: Living Room Dining Table Light Power       
    sensor.office_spot_dimmer_power:
        friendly_name: Office Spot Lights Power

light:
  - platform: group
    name: 'Inside lights'
    entities:
      - light.living_room_spot_dimmer_level
      - light.living_room_wall_dimmer_level
      - light.living_room_dining_table_dimmer_level  
      - light.office_spot_dimmer_level

  - platform: group
    name: 'Downstairs lights'
    entities:
      - light.living_room_spot_dimmer_level  
      - light.office_spot_dimmer_level
      - light.living_room_wall_dimmer_level
      - light.living_room_dining_table_dimmer_level  
      - light.entryway

  - platform: group
    name: 'Upstairs lights'
    entities:
      - light.hallway
      - light.master_bedroom
      - light.timo_room
      - light.bathroom
      - light.attic
      - light.lucas_room
      - light.emilie_room

  - platform: group
    name: 'Outdoor lights'
    entities:
      - light.front_door
      - light.backyard

script:
  alexa_turn_on_the_light:
    alias: '[Light] Turn on the light'
    sequence:
      - service: homeassistant.turn_on
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "living_room" -%}
              light.downstairs_lights
            {%- elif room == "master_bedroom" -%}
              light.master_bedroom
            {%- elif room == "lucas_room" -%}
              light.lucas_room
            {%- elif room == "timo_s_room" -%}
              light.timo_room
            {%- elif room == "emilie_s_room" -%}
              light.emilie_room
            {%- endif -%}

  alexa_turn_off_the_light:
    alias: '[Light] Turn off the light'
    sequence:
      - service: homeassistant.turn_on
        data_template:
          entity_id: >-
            {# Use the name of each Echo to determine which room the command likely came from. #}
            {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}

            {%- if room == "living_room" -%}
              light.downstairs_lights
            {%- elif room == "master_bedroom" -%}
              light.master_bedroom
            {%- elif room == "lucas_room" -%}
              light.lucas_room
            {%- elif room == "timo_s_room" -%}
              light.timo_s_room
            {%- elif room == "emilie_s_room" -%}
              light.emilie_s_room
            {%- endif -%}

automation:
  - id: 9664f92b-26b9-4cc0-a422-4a03382a86a1
    alias: '[Light] Turn of all lights when away'
    trigger:
      - platform: state
        entity_id: group.household
        from: home
        to: not_home
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
    action:
      - service: homeassistant.turn_off
        entity_id: light.inside_lights