homeassistant:
  customize:
    light.living_room_spot_dimmer_level:
      friendly_name: Living Room Spot Lights
    light.living_room_wall_dimmer_level:
      friendly_name: Living Room Wall Lights
    light.living_room_dining_table_dimmer_level:
      friendly_name: Living Room Dining Table Light       
    light.office_spot_dimmer_level:
      friendly_name: Office Spot Lights
    sensor.living_room_spot_dimmer_power:
        friendly_name: Living Room Spot Lights Power
    sensor.living_room_wall_dimmer_power:
      friendly_name: Living Room Wall Lights Power
    sensor.living_room_dining_table_dimmer_power:
      friendly_name: Living Room Dining Table Light Power       
    sensor.office_spot_dimmer_power:
        friendly_name: Office Spot Lights Power

light:
  - platform: group
    name: 'Inside lights'
    entities:
      - light.living_room_spot_dimmer_level
      - light.living_room_wall_dimmer_level
      - light.living_room_dining_table_dimmer_level  
      - light.office_spot_dimmer_level
      - light.entryway_light
      - light.hallway_light
      - light.attic_light

  - platform: group
    name: 'Downstairs lights'
    entities:
      - light.living_room_spot_dimmer_level  
      - light.office_spot_dimmer_level
      - light.living_room_wall_dimmer_level
      - light.living_room_dining_table_dimmer_level  
      - light.entryway

  - platform: group
    name: 'Upstairs lights'
    entities:
      - light.hallway_light
      - light.attic_light
      
  - platform: group
    name: 'Outdoor lights'
    entities:
      - light.backyard_light
