 ##############################################
 #                                            #
 # This package contains the scripts I use to #
 # simulate the house being occupied when the #
 # system is in Vacation mode                 #
 #                                            #
 ##############################################

 # This is used to set a random bedtime for our phantom house guest
input_datetime:
  mockupancy_bedtime:
    has_date: false
    has_time: true
    initial: '23:00'

 # The main mockupancy script...
script:
  mockupancy:
    sequence:
      # Wait until it is after 6pm and dark to start the routine
      - wait_template: "{{ states.sensor.time.state >= '18:00' and is_state('sun.sun' , 'below_horizon') }}"

      # Check that it Vacation mode is still on
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'

      # Pick a random bedtime between 10pm and midnight.
      - service: input_datetime.set_time
        data_template:
          entity_id: input_datetime.mockupancy_bedtime
          time: "{{ (range(22, 23)|random|int) }}:{{ (range(0, 59)|random|int) }}:00"

      # Start the routine, switch on the 'usual' lights
      - service: homeassistant.turn_on
        entity_id:
          - scene.relax_time

      # # Start scripts to randomise occasional lights
      # - service: script.random_entryway

      # Start scripts to randomise kids' bedtime simulation
      - service: script.random_timos_room
      - service: script.random_emilies_room

      # 1 hour before bedtime, change lighting as if TV was turned off
      - wait_template: "{{ states('sensor.time') == (((state_attr('input_datetime.mockupancy_bedtime' , 'timestamp')) - (60 * 60))|timestamp_custom('%H:%M', false)) }}"
      - service: homeassistant.turn_on
        entity_id:
          - scene.dinner_time

      # 20 minutes before bedtime, turn on kitchen lights only
      - wait_template: "{{ states('sensor.time') == (((state_attr('input_datetime.mockupancy_bedtime' , 'timestamp')) - (20 * 60))|timestamp_custom('%H:%M', false)) }}"
      - service: homeassistant.turn_on
        entity_id:
          - scene.rise_and_shine

      # Stop kitchen/master bedroom randomisation
      - service: homeassistant.turn_off
        entity_id:
          - script.random_entryway
          - script.random_timos_room
          - script.random_emilies_room

      # At 'bedtime', turn on Entryway for random time between 2 and 15 minutes
      - wait_template: "{{ states('sensor.time') == (state_attr('input_datetime.mockupancy_bedtime' , 'timestamp')|int|timestamp_custom('%H:%M', False)) }}"
      - service: light.turn_on
        entity_id: light.entrway_wall_dimmer_level
      - delay: "00:00:{{ (range(15, 59)|random|int) }}"
      - service: homeassistant.turn_off
        entity_id: light.downstairs_lights
      - delay: "00:{{ (range(2, 15)|random|int) }}:00"
      - service: light.turn_off
        entity_id: light.entrway_wall_dimmer_level

  #    # After a random time between 15 minutes and an hour, turn off the lights
      - delay: "00:{{ (range(15, 30)|random|int) }}:00"
      - service: input_boolean.turn_on
        entity_id: input_boolean.goodnight_switch

      # If light before 7am, switch off lights, stop and loop, if not run a further script first
  #    - wait_template: "{{ now().hour == 7 }}"
      - wait_template: "{{ states.sensor.time.state == '07:00' }}"
      - service_template: >
          {% if states('sun.sun' , 'below_horizon') %} script.morning_mockupancy
          {% else %} script.mockupancy_loop {% endif %}


  # A further script for if it is still dark in the morning
  morning_mockupancy:
    sequence:
      # Check that it Vacation mode is still on
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'

      # Wait a random nmber of minutes between 1 and 30 and switch on the morning lights
      - delay: "00:{{ (range(1, 30)|random|int) }}:00"
      - service: homeassistant.turn_on
        entity_id: scene.rise_and_shine

      # Wait until it is light, switch off lights and loop
      - wait_template: "{{ is_state('sun.sun' , 'above_horizon') }}"
      - service: script.mockupancy_loop


  # Randomising beditmes for the upstairs rooms
  random_timos_room:
    sequence:
      # Wait until after 8pm, and create a random delay up to 30 minutes and check if it is dark
  #    - wait_template: "{{ now().hour >= 20 }}"
      - wait_template: "{{ states.sensor.time.state >= '20:00' }}"
      - delay: "00:{{ (range(1, 30)|random|int) }}:00"
      - condition: state
        entity_id: binary_sensor.dark_outside
        state: 'on'

      # Switch light on for between 10 and 30 minutes
      - service: homeassistant.turn_on
        entity_id: light.timos_room_lamp
      - delay: "00:{{ (range(10, 30)|random|int) }}:00"
      - service: homeassistant.turn_off
        entity_id: light.timos_room_lamp

  random_emilies_room:
    sequence:
      # Wait until after 9pm, and create a random delay up to 30 minutes and check if it is dark
  #    - wait_template: "{{ now().hour >= 21 }}"
      - wait_template: "{{ states.sensor.time.state >= '21:00' }}"
      - delay: "00:{{ (range(1, 30)|random|int) }}:00"
      - condition: state
        entity_id: sun.sun
        state: below_horizon

      # Switch light on for between 10 and 30 minutes
      - service: homeassistant.turn_on
        entity_id: light.emilies_room_lamp
      - delay: "00:{{ (range(10, 30)|random|int) }}:00"
      - service: homeassistant.turn_off
        entity_id: light.emilies_room_lamp


  # Scripts that loop the ones above that need looping
  mockupancy_loop:
    sequence:
      # Switch off the lights, and make sure the calling scripts have stopped
      - service: homeassistant.turn_off
        entity_id:
          - light.inside_lights
          - script.mockupancy
      - delay: 00:05:00

      # Check that it Vacation mode is still on and restart the script for a new day
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
      - service: script.mockupancy

automation:
  - id: 27c20369-e108-462b-8c62-84999df3499c
    alias: '[Mockupancy] Turn on vacation mode'
    trigger:
      - platform: state
        entity_id: group.household
        to: not_home
        for:
          hours: 24
    mode: single
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.vacation_mode
