sensor:
  - platform: history_stats
    name: Entryway Motion Trigger Count
    entity_id: binary_sensor.entryway
    state: 'on'
    type: count
    start: '{{ now().replace(hour=6, minute=0, second=0) }}'
    duration:
      hours: 4

variable:
  last_motion:
    value: 'unknown'
    restore: true

script:
  update_last_motion:
    sequence:
      - service: variable.set_variable
        data:
          variable: last_motion
          attributes_template: >
            {
              "history_1": "{{ variable.state }}"#,
              # "history_2": "{{ variable.attributes.history_1 }}",
              # "history_3": "{{ variable.attributes.history_2 }}"
            }
        data_template:
          value: "{{ location }}"

  update_motion_entryway:
    sequence:
      - service: script.update_last_motion
        data:
          location: 'entryway'

  update_motion_kitchen:
    sequence:
      - service: script.update_last_motion
        data:
          location: 'kitchen'

  update_motion_living_room:
    sequence:
      - service: script.update_last_motion
        data:
          location: 'living_room'

  update_motion_office:
    sequence:
      - service: script.update_last_motion
        data:
          location: 'office'

  update_motion_garage:
    sequence:
      - service: script.update_last_motion
        data:
          location: 'garage'

  update_motion_front_door:
    sequence:
      - service: script.update_last_motion
        data:
          location: 'front_door'

  update_motion_backyard:
    sequence:
      - service: script.update_last_motion
        data:
          location: 'backyard'

automation:
  - id: 85d4c5f9-4c50-4097-b982-28b3a1828c38
    alias: 'Update Last Motion'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.entryway
          - binary_sensor.kitchen
          - binary_sensor.living_room
          - binary_sensor.office
          - binary_sensor.garage
          - binary_sensor.front_door_motion
          - binary_sensor.backyard_motion
        to: 'on'
    action:
      - service: variable.set_variable
        data:
          variable: last_motion
          attributes_template: >
            {
                  "history_1": "{{ variable.state }}"#,
                  # "history_2": "{{ variable.attributes.history_1 }}",
                  # "history_3": "{{ variable.attributes.history_2 }}",
                  # "history_4": "{{ variable.attributes.history_3 }}",
                  # "history_5": "{{ variable.attributes.history_4 }}",
                  # "history_6": "{{ variable.attributes.history_5 }}",
                  # "history_7": "{{ variable.attributes.history_6 }}",
                  # "history_8": "{{ variable.attributes.history_7 }}",
                  # "history_9": "{{ variable.attributes.history_8 }}",
                  # "history_10": "{{ variable.attributes.history_9 }}"
            }
        data_template:
          value: >
            {{ trigger.to_state.attributes.friendly_name|replace('motion sensor','') }}:
            {{as_timestamp(states.variable.last_motion.last_changed)| timestamp_custom('%X') }}