sensor:
  - platform: template
    sensors:
      house_movement:
        friendly_name: 'House Movement'
        entity_id: binary_sensor.entryway, binary_sensor.kitchen, binary_sensor.living_room, binary_sensor.office, binary_sensor.garage
        value_template: >-
          {% if is_state('binary_sensor.entryway', 'on') or is_state("binary_sensor.kitchen", "on") or is_state("binary_sensor.living_room", "on") or is_state("binary_sensor.office", "on") or is_state("binary_sensor.garage", "on") %}
            Movement detected
          {% else %}
            No movement
          {% endif %}

      outdoor_movement:
        friendly_name: 'Outdoor Movement'
        entity_id: binary_sensor.front_door_motion, binary_sensor.backyard_motion
        value_template: >-
          {% if is_state('binary_sensor.front_door_motion', 'on') or is_state("binary_sensor.backyard_motion", "on") %}
            Movement detected
          {% else %}
            No movement
          {% endif %}          