powercalc:
  scan_interval: 00:01:00 #Each minute
  power_sensor_naming: "{} Power"
  energy_sensor_naming: "{} Energy"
  create_energy_sensors: true

sensor:
  - platform: powercalc
    entity_id: light.hood_light
    manufacturer: Siemens
    model: LF98BIR55 
    standby_usage: 0
    disable_standby_usage: true
    linear:
      min_power: 0.2
      max_power: 12
  - platform: powercalc
    entity_id: switch.hood_power
    manufacturer: Siemens
    model: LF98BIR55 
    standby_usage: 0.31
    disable_standby_usage: false
    fixed:
      power: 75 #need to check
  - platform: powercalc
    entity_id: device_tracker.living_room_tv
    manufacturer: Panasonic
    model: TV-P50VT20EA
    standby_usage: 0.4
    disable_standby_usage: false
    fixed:
      power: 212
  - platform: powercalc
    entity_id: device_tracker.living_room_xbox_one
    manufacturer: Microsoft
    model: Xbox One
    standby_usage: 0.22
    disable_standby_usage: false
    fixed:
      power: 80 #need to check
  - platform: powercalc
    entity_id: device_tracker.home_alarm
    manufacturer: Konnected
    model: 6-Zone Konnected Alarm Panel
    standby_usage: 0
    disable_standby_usage: true
    fixed:
      power: 5 #need to check


template:
  - sensor:
      - kitchen_refrigerator_power:
        unique_id: 331f2e5a-bdab-4562-81ca-bd6a23f3f1df
        state: 13.125
        unit_of_measurement: W
        device_class: power


