binary_sensor:
  - platform: template
    sensors:
      washing_machine_on:
        friendly_name: "Washing Machine"
        device_class: power
        delay_on:
          minutes: 2
        delay_off: 
          minutes: 2
        value_template: >
          {{ states('sensor.attic_washing_machine_current_consumption')| float > 10 }}
      dryer_on:
        friendly_name: "Dryer"
        device_class: power
        delay_off:
          minutes: 5
        value_template: >
          {{ states('sensor.attic_tumble_dryer_current_consumption')| float > 150 }}
      vieratv_on:
        friendly_name: 'Living Room TV'
        device_class: power
        value_template: >
          {{ is_state('device_tracker.living_room_tv', 'home') }}
      amplifier_on:
        friendly_name: "Amplifier"
        device_class: power
        # delay_off:
        #   minutes: 2
        value_template: >
          {{ states('sensor.living_room_amplifier_current_consumption')| float > 10 }}