template:
  - binary_sensor:
      - name: Washing Machine
        unique_id: 2682f3e4-48b8-4488-a436-ee682c637bb3
        delay_on:
          minutes: 1
        delay_off: 
          minutes: 1
        state: >
          {{ states('sensor.attic_washing_machine_power')| float > 0 }}
      - name: Dryer 
        unique_id: 5c6fefb2-27ad-47b7-b51b-227d6cb4328e
        delay_off:
          minutes: 5
        state: >
          {{ states('sensor.attic_tumble_dryer_power')| float > 300 }}
      - name: Dishwasher
        unique_id: 176f0e85-977d-4882-96ad-606071960650
        state: >
          {{ states('sensor.kitchen_dishwasher_power')| float > 0 }}
      - name: Vieratv
        unique_id: be7af9a4-ce77-45a3-8c58-84ddf60ce341
        state: >
          {{ is_state('device_tracker.living_room_tv', 'home') }}
      - name: Amplifier
        unique_id: a5202f4d-362c-4d66-9619-4befc649477e
        state: >
          {{ states('sensor.living_room_amplifier_power')| float > 10 }}
      - name: Pool Filter
        unique_id: 7481a18e-1db1-4aa0-8906-133ec2fb4bef
        state: >
          {{ states('sensor.backyard_pool_filter_power')| float > 45 }}
      - name: Quooker
        unique_id: 6f54c468-8b7d-442c-ad4d-092931867d86
        state: >
          {{ states('sensor.quooker_power')| float > 0 }}

automation:
  - id: ef7a15bf-f601-4e75-9e2a-f3a796d37750
    alias: '[Notification] Amplifier on when TV is turned off'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.vieratv
        from: 'on'
        to: 'off'
    mode: single
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.amplifier
          state: 'on'
    action:
      - service: notify.mobile_app_sm_g986b
        data:
          title: TV turned off
          message: TV is turned off, dont't forget to turn of the amplifier
          data:
            channel: Alert
            tag: alert
      - service: notify.mobile_app_iphone_van_stephanie
        data:
          title: TV turned off
          message: TV is turned off, dont't forget to turn of the amplifier
          data:
            push:
              thread-id: "alert"
              presentation_options:
                - alert
                - badge

  - id: f1840add-37b8-4936-9160-cbef20e73825
    alias: '[Notification] Washing machine finished'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine
        from: 'on'
        to: 'off'
    mode: single
    action:
      # - service: notify.mobile_app_sm_g986b
      #   data:
      #     message: Washing machine is finished
      #     data:
      #       channel: Alert
      #       tag: alert
      - service: notify.mobile_app_iphone_van_stephanie
        data:
          message: Washing machine is finished
          data:
            push:
              thread-id: "alert"
              presentation_options:
                - alert
                - badge

  - id: 1a0462f8-5104-4019-920e-dbb682ec9a5e
    alias: '[Notification] Tumble dryer finished'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.dryer
        from: 'on'
        to: 'off'
    mode: single
    action:
      # - service: notify.mobile_app_sm_g986b
      #   data:
      #     message: Tumble dryer is finished
      #     data:
      #       channel: Alert
      #       tag: alert
      - service: notify.mobile_app_iphone_van_stephanie
        data:
          message: Tumble dryer is finished
          data:
            push:
              thread-id: "alert"
              presentation_options:
                - alert
                - badge
