binary_sensor:
  - platform: template
    sensors:
      washing_machine_on:
        friendly_name: "Washing Machine"
        device_class: power
        delay_on:
          minutes: 1
        delay_off: 
          minutes: 1
        value_template: >
          {{ states('sensor.shelly_shplg_s_f8d1ea_current_consumption')| float > 10 }}
      dryer_on:
        friendly_name: "Tumble Dryer" 
        device_class: power
        delay_off:
          minutes: 5
        value_template: >
          {{ states('sensor.shelly_shplg_s_f8d1fa_current_consumption')| float > 300 }}
      vieratv_on:
        friendly_name: 'Living Room TV'
        device_class: power
        value_template: >
          {{ is_state('device_tracker.living_room_tv', 'home') }}
      amplifier_on:
        friendly_name: "Amplifier"
        device_class: power
        # delay_off:
        #   minutes: 2
        value_template: >
          {{ states('sensor.shelly_shplg_s_8013cd_current_consumption')| float > 10 }}