powercalc:
  scan_interval: 00:01:00 #Each minute
  power_sensor_naming: "{} Powersensor"
  create_energy_sensors: true

sensor:
  - platform: powercalc
    entity_id: light.hood_light
  - platform: powercalc
    entity_id: switch.hood_power
  - platform: powercalc
    entity_id: device_tracker.living_room_tv
  - platform: powercalc
    entity_id: device_tracker.living_room_xbox_one
  - platform: powercalc
    entity_id: device_tracker.home_alarm
