binary_sensor:
  - platform: template
    sensors:
      washing_machine_on:
        friendly_name: "Washing machine on"
        device_class: power
        delay_on:
          minutes: 2
        delay_off: 
          minutes: 2
        value_template: >
          {{ states('sensor.attic_washing_machine_current_consumption')| float > 10 }}
      dryer_on:
        friendly_name: "Dryer on"
        device_class: power
        delay_off:
          minutes: 2
        value_template: >
          {{ states('sensor.attic_dryer_current_consumption')| float > 400 }}
      amplifier_on:
        friendly_name: "Amplifier on"
        device_class: power
        # delay_off:
        #   minutes: 2
        value_template: >
          {{ states('sensor.living_room_amplifier_current_consumption')| float > 10 }}