homeassistant:
  customize:
    cover.master_bedroom_roller_shutter_level:
      friendly_name: Master Bedroom Roller Shutter
    cover.lucas_room_roller_shutter_level:
      friendly_name: Lucas Room Roller Shutter
    cover.backyard_sunscreen:
      friendly_name: Backyard Sunscreen
    input_boolean.shuttersupdate:
      friendly_name: Auto Shutter
      icon: mdi:window-shutter    

automation:
  - alias: Covers - Open in the morning
    initial_state: 'true'
    condition:
    - condition: state
      entity_id: input_boolean.shuttersupdate
      state: 'on'
    - condition: state
      entity_id: group.household
      state: home
#    - condition # only on weekdays
    trigger:
    - platform: time
      at: 08:30:00
    action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.master_bedroom_roller_shutter_level
        position: 100

  - alias: Covers - Close in the evening
    initial_state: 'true'
    condition:
    - condition: state
      entity_id: input_boolean.shuttersupdate
      state: 'on'
    - condition: state
      entity_id: group.household
      state: home
    trigger:
    - platform: sun
      event: sunset
    - platform: state
      entity_id: alarm_control_panel.Konnected_Alarm
      state: armed_home
    action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.master_bedroom_roller_shutter_level
        position: 10

  - alias: Covers - Open
    initial_state: 'true'
    condition:
    - condition: state
      entity_id: input_boolean.shuttersupdate
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.br_temperature
      below: 25
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    trigger:
    - platform: state
      entity_id: group.household
      from: not-home
      to: home
    action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.master_bedroom_roller_shutter_level
        position: 100

  - alias: Covers - Close
    initial_state: 'true'
    condition:
    - condition: state
      entity_id: input_boolean.shuttersupdate
      state: 'on'
    trigger:
    - platform: state
      entity_id: group.household
      from: home
      to: not_home
    - platform: numeric_state
      entity_id: sensor.br_temperature
      above: 25
    action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.master_bedroom_roller_shutter_level
        position: 0
        entity_id: cover.Lucas_room_roller_shutter_level
        position: 0

  - alias: Covers - Open when smoke or CO detected
    initial_state: 'true'
    condition:
    trigger:
    - platform: state
      entity_id: sensor.entryway_nest_protect_smoke_status
      from: "ok
    - platform: state
      entity_id: sensor.entryway_nest_protect_co_status
      from: "ok
    - platform: state
      entity_id: sensor.hallway_nest_protect_smoke_status
      from: "ok
    - platform: state
      entity_id: sensor.hallway_nest_protect_co_status
      from: "ok
    - platform: state
      entity_id: sensor.attic_nest_protect_smoke_status
      from: "ok
    - platform: state
      entity_id: sensor.attic_nest_protect_co_status
      from: "ok
    action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.master_bedroom_roller_shutter_level
        position: 100
        entity_id: cover.Lucas_room_roller_shutter_level
        position: 100

  - alias: Covers - Status Update
    trigger:
      - platform: event
        event_type: call_service
        event_data:
          domain: cover
          service: set_cover_position
    condition:
      - condition: template
        value_template: "{{ state_attr(trigger.event.data.service_data.entity_id, 'current_position') | int != trigger.event.data.service_data.position | int }}"
    action:
      - delay: "00:00:01"
      - service: cover.set_cover_position
        data_template:
          entity_id: "{{ trigger.event.data.service_data.entity_id }}"
          position: "{{ trigger.event.data.service_data.position }}"

input_boolean:
  shuttersupdate:
    initial: on