homeassistant:
  customize:
    cover.master_bedroom_roller_shutter_level:
      friendly_name: Master Bedroom Roller Shutter
    cover.lucas_room_roller_shutter_level:
      friendly_name: Lucas Room Roller Shutter
    cover.backyard_sunscreen:
      friendly_name: Backyard Sunscreen
    input_boolean.shuttersupdate:
      friendly_name: Auto Shutter
      icon: mdi:window-shutter    

automation:
  - alias: Shutters - Set Cover Position
    initial_state: 'true'
    trigger:
      platform: time
      at: "08:00:00"
    action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.master_bedroom_roller_shutter_level
        position: 50

  - alias: Roller Shutter Status Update
    trigger:
      - platform: event
        event_type: call_service
        event_data:
          domain: cover
          service: set_cover_position
    condition:
      - condition: template
        value_template: "{{ state_attr(trigger.event.data.service_data.entity_id, 'current_position') | int != trigger.event.data.service_data.position | int }}"
    action:
      - delay: "00:00:01"
      - service: cover.set_cover_position
        data_template:
          entity_id: "{{ trigger.event.data.service_data.entity_id }}"
          position: "{{ trigger.event.data.service_data.position }}"

script:
  master_bedroom_shutter_open:
    alias: Shutters - Master Bedroom Shutter Open
    sequence:
      - service: cover.open_cover
        data:
          entity_id: cover.master_bedroom_roller_shutter_level
          position: 50

  lucas_room_shutter_open:
    alias: Shutters - Lucas Room Shutter Open
    sequence:
      - service: cover.open_cover
        data:
          entity_id: cover.lucas_room_roller_shutter_level

  master_bedroom_shutter_almost_close:
    alias: Shutters - Master Bedroom Shutter Almost Close
    sequence:
      - service: cover.set_cover_position
        data:
          entity_id: cover.master_bedroom_roller_shutter_level
          position: 10

  lucas_room_shutter_almost_close:
    alias: Shutters - Lucas Room Shutter Almost Close
    sequence:
      - service: cover.set_cover_position
        data:
          entity_id: cover.lucas_room_roller_shutter_level
          position: 10

  master_bedroom_shutter_close:
    alias: Shutters - Master Bedroom Shutter Close
    sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.demo


  lucas_room_shutter_close:
    alias: Shutters - Lucas Room Shutter Close
    sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.demo


input_boolean:
  shuttersupdate:
    initial: on

