homeassistant:
  customize:
    cover.master_bedroom_roller_shutter_level:
      friendly_name: Master Bedroom Roller Shutter
    cover.lucas_room_roller_shutter_level:
      friendly_name: Lucas Room Roller Shutter
    cover.backyard_sunscreen:
      friendly_name: Backyard Sunscreen
    input_boolean.shuttersupdate:
      friendly_name: Auto Shutter
      icon: mdi:window-shutter    

automation:
  - alias: Shutters - Set Cover Position
    initial_state: 'true'
    trigger:
      platform: time
      at: "07:15:00"
    action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.demo
        position: 50


script:
  master_bedroom_shutter_open:
    alias: Shutters - Master Bedroom Shutter Open
    sequence:
      - service: cover.open_cover
        data:
          entity_id: cover.demo
          position: 50

  lucas_room_shutter_open:
    alias: Shutters - Lucas Room Shutter Open
    sequence:
      - service: cover.open_cover
        data:
          entity_id: cover.balcony01

  master_bedroom_shutter_almost_close:
    alias: Shutters - Master Bedroom Shutter Almost Close
    sequence:
      - service: cover.set_cover_position
        data:
          entity_id: cover.demo
          position: 95

  lucas_room_shutter_almost_close:
    alias: Shutters - Lucas Room Shutter Almost Close
    sequence:
      - service: cover.set_cover_position
        data:
          entity_id: cover.demo
          position: 95

  master_bedroom_shutter_close:
    alias: Shutters - Master Bedroom Shutter Close
    sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.demo


  lucas_room_shutter_close:
    alias: Shutters - Lucas Room Shutter Close
    sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.demo


input_boolean:
  shuttersupdate:
    initial: on

