homeassistant:
  customize:
    cover.master_bedroom_roller_shutter_level:
      friendly_name: Master Bedroom Roller Shutter
    cover.lucas_room_roller_shutter_level:
      friendly_name: Lucas Room Roller Shutter
    cover.backyard_sunscreen:
      friendly_name: Backyard Sunscreen
    input_boolean.shuttersupdate:
      friendly_name: Auto Shutter
      icon: mdi:window-shutter    

automation:
  - alias: Covers - Open in the morning in Master Bedroom
    initial_state: 'true'
    condition:
    - condition: state
      entity_id: input_boolean.shuttersupdate
      state: 'on'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    trigger:
    - platform: time
      at: "08:30:00"
    action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.master_bedroom_roller_shutter_level
        position: 100

  - alias: Covers - Open in the morning in Lucas Room
    initial_state: 'true'
    condition:
    - condition: state
      entity_id: input_boolean.shuttersupdate
      state: 'on'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    trigger:
    - platform: time
      at: "09:00:00"
    action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.lucas_room_roller_shutter_level
        position: 100

  - alias: Covers - Open in the morning during the weekends and holidays
    initial_state: 'true'
    condition:
    - condition: state
      entity_id: input_boolean.shuttersupdate
      state: 'on'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'off'
    trigger:
    - platform: time
      at: "11:00:00"
    action:
    - service: cover.set_cover_position
      data:
        entity_id:
          - cover.master_bedroom_roller_shutter_level
          - cover.lucas_room_roller_shutter_level
        position: 100


  - alias: Covers - Close in the evening
    initial_state: 'true'
    condition:
    - condition: state
      entity_id: input_boolean.shuttersupdate
      state: 'on'
    - condition: state
      entity_id: group.household
      state: 'home'
    trigger:
    - platform: sun
      event: sunset
    - platform: state
      entity_id: alarm_control_panel.Konnected_Alarm
      to: 'armed_home'
    action:
    - service: cover.set_cover_position
      data:
        entity_id:
          - cover.master_bedroom_roller_shutter_level
          - cover.lucas_room_roller_shutter_level
        position: 10

  - alias: Covers - Open when arriving home
    initial_state: 'true'
    condition:
    - condition: state
      entity_id: input_boolean.shuttersupdate
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.br_temperature
      below: 25
    - condition: state
      entity_id: sun.sun
      state: above_horizon
    trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
    action:
    - service: cover.set_cover_position
      data:
        entity_id:
          - cover.master_bedroom_roller_shutter_level
          - cover.lucas_room_roller_shutter_level
        position: 100

  - alias: Covers - Close when noone at home
    initial_state: 'true'
    condition:
    - condition: state
      entity_id: input_boolean.shuttersupdate
      state: 'on'
    trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'
    - platform: numeric_state
      entity_id: sensor.br_temperature
      above: 25
    action:
    - service: cover.set_cover_position
      data:
        entity_id:
          - cover.master_bedroom_roller_shutter_level
          - cover.lucas_room_roller_shutter_level
        position: 0

  - alias: Covers - Open when smoke or CO detected
    initial_state: 'true'
    condition:
    trigger:
    - platform: state
      entity_id: sensor.entryway_nest_protect_smoke_status
      from: 'ok'
    - platform: state
      entity_id: sensor.entryway_nest_protect_co_status
      from: 'ok'
    - platform: state
      entity_id: sensor.hallway_nest_protect_smoke_status
      from: 'ok'
    - platform: state
      entity_id: sensor.hallway_nest_protect_co_status
      from: 'ok'
    - platform: state
      entity_id: sensor.attic_nest_protect_smoke_status
      from: 'ok'
    - platform: state
      entity_id: sensor.attic_nest_protect_co_status
      from: 'ok'
    action:
    - service: cover.set_cover_position
      data:
        entity_id:
          - cover.master_bedroom_roller_shutter_level
          - cover.lucas_room_roller_shutter_level
        position: 100

input_boolean:
  shuttersupdate:
    initial: on