homeassistant:
  customize:
    binary_sensor.entryway_nest_protect_online:
      friendly_name: Entryway Nest Protect
    binary_sensor.hallway_nest_protect_online:
      friendly_name: Hallway Nest Protect
    binary_sensor.attic_nest_protect_online:
      friendly_name: Attic Nest Protect

automation:
  - alias: '[Nest] Nest Protect Offline'
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id:
        - binary_sensor.entryway_nest_protect_online
        - binary_sensor.hallway_nest_protect_online
        - binary_sensor.attic_nest_protect_online
      from: 'on'
      to: 'off'
    action:
    - service: persistent_notification.create
      data_template:
        message: "{{ trigger.entity_id.name }} reported offline."
        title: Nest Protect Offline
    - service: notify.html5_galaxy_s9
      data_template:
        message: "{{ trigger.entity_id.name }} reported offline."
        title: Nest Protect Offline

  - alias: '[Nest] Smoke/CO Detected'
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: sensor.smoke_co_detection
      from: 'All clear'
    action:
    - service: persistent_notification.create
      data_template:
        message: "Smoke or CO detected"
        title: Nest Protect
    - service: notify.html5_galaxy_s9
      data_template:
        message: "Smoke or CO detected"
        title: Nest Protect

sensor:
  - platform: template
    sensors:
      smoke_co_detection:
        friendly_name: 'Smoke/CO Detection'
        entity_id: sensor.entryway_nest_protect_smoke_status, sensor.hallway_nest_protect_smoke_status, sensor.attic_nest_protect_smoke_status, sensor.entryway_nest_protect_co_status, sensor.hallway_nest_protect_co_status, sensor.attic_nest_protect_co_status
        value_template: >-
          {% if not is_state("sensor.entryway_nest_protect_smoke_status", "Ok") or not is_state("sensor.hallway_nest_protect_smoke_status", "Ok") or not is_state("sensor.attic_nest_protect_smoke_status", "Ok")  %}
            Smoke Detected
          {% elif not is_state("sensor.entryway_nest_protect_co_status", "Ok") or not is_state("sensor.hallway_nest_protect_co_status", "Ok") or not is_state("sensor.attic_nest_protect_co_status", "Ok")  %}
            CO Detected
          {% else %}
            All clear 
          {% endif %}