homeassistant:
  customize:
    binary_sensor.entryway_nest_protect_online:
      friendly_name: Entryway Nest Protect
    binary_sensor.hallway_nest_protect_online:
      friendly_name: Hallway Nest Protect
    binary_sensor.attic_nest_protect_online:
      friendly_name: Attic Nest Protect
    sensor.entryway_nest_protect_smoke_status:
      icon: mdi:smoke-detector
    sensor.hallway_nest_protect_smoke_status:
      icon: mdi:smoke-detector
    sensor.attic_nest_protect_smoke_status:
      icon: mdi:smoke-detector
    sensor.entryway_nest_protect_co_status:
      icon: mdi:smoke-detector
    sensor.hallway_nest_protect_co_status:
      icon: mdi:smoke-detector
    sensor.attic_nest_protect_co_status:
      icon: mdi:smoke-detector

automation:
  - id: f1ac429c-e0c6-4859-a3a1-d271136334fa
    alias: '[Nest] Smoke Detected'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.entryway_nest_protect_smoke_status
        to: emergency
      - platform: state
        entity_id: sensor.hallway_nest_protect_smoke_status
        to: emergency
      - platform: state
        entity_id: sensor.attic_nest_protect_smoke_status
        to: emergency
      - platform: state
        entity_id: sensor.entryway_nest_protect_smoke_status
        to: warning
      - platform: state
        entity_id: sensor.hallway_nest_protect_smoke_status
        to: warning
      - platform: state
        entity_id: sensor.attic_nest_protect_smoke_status
        to: warning
    action:
      - service: persistent_notification.create
        data_template:
          message: "Smoke detected"
          title: Nest Protect
      - service: notify.mobile_app_sm_g960f
        data_template:
          message: "Smoke detected"
          title: Nest Protect

  - id: a3f8f81e-db50-480b-87a5-146530934099
    alias: '[Nest] CO Detected'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.entryway_nest_protect_co_status
        to: emergency
      - platform: state
        entity_id: sensor.hallway_nest_protect_co_status
        to: emergency
      - platform: state
        entity_id: sensor.attic_nest_protect_co_status
        to: emergency
      - platform: state
        entity_id: sensor.entryway_nest_protect_co_status
        to: warning
      - platform: state
        entity_id: sensor.hallway_nest_protect_co_status
        to: warning
      - platform: state
        entity_id: sensor.attic_nest_protect_co_status
        to: warning
    action:
      - service: persistent_notification.create
        data_template:
          message: "CO detected"
          title: Nest Protect
      - service: notify.mobile_app_sm_g960f
        data_template:
          message: "CO detected"
          title: Nest Protect

  - id: d28bb847-8061-473b-b632-7a7d684cee78
    alias: '[Nest] Turn on lights with an emergency'
    trigger:
      - platform: state
        entity_id: sensor.entryway_nest_protect_smoke_status
        to: emergency
      - platform: state
        entity_id: sensor.hallway_nest_protect_smoke_status
        to: emergency
      - platform: state
        entity_id: sensor.attic_nest_protect_smoke_status
        to: emergency
      - platform: state
        entity_id: sensor.entryway_nest_protect_co_status
        to: emergency
      - platform: state
        entity_id: sensor.hallway_nest_protect_co_status
        to: emergency
      - platform: state
        entity_id: sensor.attic_nest_protect_co_status
        to: emergency
    action:
      - service: scene.turn_on
        entity_id: scene.emergency