homeassistant:
  customize:
    binary_sensor.entryway_nest_protect_online:
      friendly_name: Entryway Nest Protect
    binary_sensor.hallway_nest_protect_online:
      friendly_name: Hallway Nest Protect
    binary_sensor.attic_nest_protect_online:
      friendly_name: Attic Nest Protect
    sensor.entryway_nest_protect_smoke_status:
      icon: mdi:smoke-detector
    sensor.hallway_nest_protect_smoke_status:
      icon: mdi:smoke-detector
    sensor.attic_nest_protect_smoke_status:
      icon: mdi:smoke-detector
    sensor.entryway_nest_protect_co_status:
      icon: mdi:smoke-detector
    sensor.hallway_nest_protect_co_status:
      icon: mdi:smoke-detector
    sensor.attic_nest_protect_co_status:
      icon: mdi:smoke-detector
