input_boolean:
  # Vacation Mode Toggle: Used as the condition for vacation lighting blueprint
  vacation_mode:
    name: Vacation Mode
    icon: mdi:beach

sensor:
  # Replay Sensor - Make a new one for each light to monitor
  # All sensors will have naming convention "sensor.replay_xxxxx"
  - platform: history_stats
    name: "replay_attic_light"
    entity_id: light.attic_light
    state: "on"
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30
    
  - platform: history_stats
    name: "replay_bathroom_light"
    entity_id: light.bathroom_light
    state: "on"
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30
    
  - platform: history_stats
    name: "replay_entryway_wall_light"
    entity_id: light.entryway_wall_light
    state: "on"
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30
    
  - platform: history_stats
    name: "replay_kitchen_light"
    entity_id: light.kitchen_light
    state: "on"
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30
    
  - platform: history_stats
    name: "replay_living_room_dining_table_light"
    entity_id: light.living_room_dining_table_light
    state: "on"
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30
    
  - platform: history_stats
    name: "replay_living_room_spot_light"
    entity_id: light.living_room_spot_light
    state: "on"
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30
    
  - platform: history_stats
    name: "replay_living_room_wall_light"
    entity_id: light.living_room_wall_light
    state: "on"
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30
    
  - platform: history_stats
    name: "replay_office_desk_light"
    entity_id: light.office_desk_light
    state: "on"
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30
    
  - platform: history_stats
    name: "replay_office_spot_light"
    entity_id: light.office_spot_light
    state: "on"
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30
    
  - platform: history_stats
    name: "replay_timo_s_room_light"
    entity_id: light.timo_s_room_light
    state: "on"
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

automation:    
  - id: c2a8a007-ea9e-4bfd-9a44-4bc81bba6edf
    alias: '[Vacation] Turn device off when vacation mode is enabled'
    trigger:
      - platform: state
        entity_id: input_boolean.vacation_mode
        from: "off"
        to: "on"
    action:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.quooker  

  - id: b52c88d1-ed6f-4031-b5c5-360c0d07f6c0
    alias: '[Vacation] Turn device on when vacation mode is enabled'
    trigger:
      - platform: state
        entity_id: input_boolean.vacation_mode
        from: "on"
        to: "off"
    action:
      - service: switch.turn_on
        target:
          entity_id:
            - switch.quooker              