alias: Arm Konnected
initial_state: 'true'
condition:
- condition: state
  entity_id: input_boolean.konnectedupdate
  state: 'on'
- condition: template
  value_template: "{%- if states.automation.disarm_konnected_from_away.attributes.last_triggered\
    \ -%}\n  {{ (as_timestamp(now()) - as_timestamp(states.automation.disarm_konnected_from_away.attributes.last_triggered))\
    \ > 240 }}\n{%- else -%}\n  true\n{%- endif -%}\n"
- condition: template
  value_template: '{{ states(''input_select.konnectedstatus'') != ''armed_away''
    }}'
- condition: template
  value_template: '{{ states(''alarm_control_panel.konnected_alarm'') != ''triggered''
    }}'
trigger:
- platform: state
  entity_id: group.household
  from: home
  to: not_home
- platform: state
  entity_id: group.household
  from: 'home'
  to: 'not_home'
  for: 00:05:00
action:
- service: homeassistant.turn_on
  entity_id: script.konnectedaway
id: 2b81bdb0aa0b4c409d4bb03b1a04a336

