alias: Cancel thermostat ETA
initial_state: 'true'
condition:
- condition: template
  value_template: '{{ states.sensor.retsinagaard_eta != "1970-01-01 00:00:00+00:00"
    }}'
trigger:
- platform: state
  entity_id: group.household
  from: not_home
  to: home
- platform: template
  value_template: "{% if is_state_attr('proximity.home', 'dir_of_travel', 'towards') %}false{% endif %}"
  for: '00:05:00'
action:
- service: homeassistant.turn_on
  entity_id: script.nest_cancel_eta
- service: homeassistant.turn_on
  data_template:
    entity_id: "{%- if states('switch.living_room_away') == 'on' -%}\n  switch.living_room_away\n\
      {%- endif -%}\n"
id: b89f4253b34949fb91cdccce055ad59b
