alias: Daily snapshot
initial_state: 'true'
trigger:
- platform: time
  at: '2:00:00'
condition:
- condition: state
  entity_id: person.dennis
  state: 'home'
action:
- data_template:
    name: Automated backup {{ now().strftime('%Y-%m-%d') }}
    password: mN$#3J4geo5$
  service: hassio.snapshot_full
id: 5fd18e960de547e9a2c9d785f76307e6
