alias: Deactivate siren
initial_state: 'true'
trigger:
- platform: state
  entity_id: alarm_control_panel.Konnected_Alarm
  to: triggered
  for: 00:20:00
- platform: state
  entity_id: alarm_control_panel.Konnected_Alarm
  to: disarmed
action:
- service: switch.turn_off
  entity_id: switch.siren
- service: switch.turn_off
  entity_id: switch.backyard_siren
id: dd7b5484487942d08e18f10f57623daf
