alias: Disable thermostat away
initial_state: 'true'
condition:
- condition: template
  value_template: '{{states(''input_select.konnectedstatus'') == ''disarmed'' and
    states(''group.thermostats'') == ''on''}}

    '
trigger:
- platform: time_pattern
  minutes: /5
  seconds: 0
action:
- service: homeassistant.turn_off
  data_template:
    entity_id: "{%- if states('switch.living_room_away') == 'on' -%}\n  switch.living_room_away\n\
      {%- endif -%}\n"
id: 61fe50480e91481d90126455520f5d9d
