alias: Disarm Konnected in the morning
initial_state: 'true'
condition:
  condition: and
  conditions:
  - condition: state
    entity_id: group.household
    state: home
  - condition: state
    entity_id: input_boolean.konnectedupdate
    state: 'on'
trigger:
- platform: time
  at: 06:00:00
action:
- service: homeassistant.turn_on
  entity_id: script.konnectedstandby
id: 55aa7945211b4beb9b11b432025bd919
