alias: Low Ring Battery Notification
initial_state: 'on'
trigger:
- platform: numeric_state
  entity_id: sensor.ring_front_door_battery
  below: 10
- platform: numeric_state
  entity_id: sensor.ring_front_door_battery
  below: 5
#  - platform: numeric_state
#    entity_id: sensor.ring_backyard_battery
#    below: 10
#  - platform: numeric_state
#    entity_id: sensor.ring_backyard_battery
#    below: 5
action:
- service: persistent_notification.create
  data_template:
    message: "{{ trigger.entity_id }} reported low battery, please charge."
    title: Ring Battery Low
- service: notify.html5_galaxy_s9
  data_template:
    message: "{{ trigger.entity_id }} reported low battery, please charge."
    title: Ring Battery Low
