alias: Motion in backyard
initial_state: 'true'
trigger:
- platform: state
  entity_id: binary_sensor.ring_backyard_motion
  to: 'on'
condition:
  condition: or
  conditions:
  - condition: state
    entity_id: alarm_control_panel.Konnected_Alarm
    state: armed_away
  - condition: state
    entity_id: alarm_control_panel.Konnected_Alarm
    state: armed_home
action:
- service: homeassistant.turn_on
  entity_id: script.backyardmotion
