alias: 'Set dark theme for the night'
initial_state: true
trigger:
  - platform: sun
    event: sunset
    offset: '+00:00:00'
action:
  - service: frontend.set_theme
    data:
      name: Homekit Gray Dark