alias: Set thermostat ETA
initial_state: 'true'
condition:
  condition: and
  conditions:
  - condition: state
    entity_id: group.household
    state: not_home
  - condition: state
    entity_id: binary_sensor.retsinagaard_away
    state: 'on'
trigger:
  platform: template
  value_template: "{%- if is_state_attr('proximity.home', 'dir_of_travel', 'towards')\
    \ -%}\n  true\n{%- endif -%}\n"
action:
- service: homeassistant.turn_on
  entity_id: script.nest_update_eta
id: 1ac37a30d0804f4c9f7647c41b452961
