alias: 'theme selector input_select 5'
initial_state: true
trigger:
  - platform: state
    entity_id: input_select.theme_selector
    to: 'Standard Blue Light'
action:
  - service: frontend.set_theme
    data:
      name: Standard Blue Light
  - service: homeassistant.turn_off
    data:
      entity_id: group.theme_selector