alias: 'theme selector input_select 3'
initial_state: true
trigger:
  - platform: state
    entity_id: input_select.theme_selector
    to: 'Homekit Blue Light'
action:
  - service: frontend.set_theme
    data:
      name: Homekit Blue Light
  - service: homeassistant.turn_off
    data:
      entity_id: group.theme_selector