alias: Trigger Alarm
initial_state: 'true'
trigger:
- platform: state
  entity_id: alarm_control_panel.Konnected_Alarm
  to: triggered
action:
- service: homeassistant.turn_on
  entity_id: script.konnectedtrigger
id: ae82023c1efb4cfd9274f983d7917b00
