alias: Update Notifications
initial_state: 'on'
condition:
- condition: template
  value_template: '{{ states.sensor.latest_version.state != states.sensor.current_version.state }}'
trigger:
- platform: time
  at: 04:00:00
- platform: state
  entity_id: person.dennis
  from: 'not_home'
  to: 'home'
action:
- delay: 00:30:00
- service: notify.html5_galaxy_s9_edge
  data:
    title: Home Assistant Update
    message: "Version {{ states.sensor.latest_version.state }} is available!"
    target:
      - galaxy_s9_chrome
      - surfacebook_chrome
id: 02e8ce2646044bb5b284e44b56e290d1
