konnected:
  access_token: !secret konnected_access_token
#  api_host: !secret konnected_api_host
  devices:
    - id: !secret konnected_device_id
      binary_sensors:
        - zone: 1
          type: motion
          name: 'Entryway'
        - zone: 2
          type: motion
          name: 'Kitchen'
        - zone: 3
          type: motion
          name: 'Living Room'
        - zone: 4
          type: motion
          name: 'Office'
        - zone: 5
          type: motion
          name: 'Garage'
      switches:
        - zone: out
          name: 'Siren'
      blink: false

alarm_control_panel:
  - platform: manual
    name: Konnected Alarm
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 300
      delay_time: 20

  - platform: alexa_media
    name: Alexa Guard
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 300
      delay_time: 20

input_boolean:
  konnectedupdate:
    name: Alarm Updates
    initial: on
    icon: mdi:security  

automation:
  - alias: Arm Konnected
    initial_state: 'true'
    condition:
    - condition: state
      entity_id: input_boolean.konnectedupdate
      state: 'on'
    - condition: template
      value_template: "{%- if states.automation.disarm_konnected_from_away.attributes.last_triggered\
        \ -%}\n  {{ (as_timestamp(now()) - as_timestamp(states.automation.disarm_konnected_from_away.attributes.last_triggered))\
        \ > 240 }}\n{%- else -%}\n  true\n{%- endif -%}\n"
    - condition: template
      value_template: '{{ states(''input_select.konnectedstatus'') != ''armed_away''
        }}'
    - condition: template
      value_template: '{{ states(''alarm_control_panel.konnected_alarm'') != ''triggered''
        }}'
    trigger:
    - platform: state
      entity_id: group.household
      from: home
      to: not_home
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'
      for: 00:05:00
    action:
    - service: homeassistant.turn_on
      entity_id: script.konnectedaway
    id: 2b81bdb0aa0b4c409d4bb03b1a04a336

  - alias: Deactivate siren
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: alarm_control_panel.Konnected_Alarm
      to: triggered
      for: 00:20:00
    - platform: state
      entity_id: alarm_control_panel.Konnected_Alarm
      to: disarmed
    action:
    - service: switch.turn_off
      entity_id: switch.siren
    - service: switch.turn_off
      entity_id: switch.backyard_siren
    id: dd7b5484487942d08e18f10f57623daf  
    
script:
  - konnectedaway:
      alias: 'Konnected Arm'
      sequence:
        - service: input_select.select_option
          data:
            entity_id: input_select.konnectedstatus
            option: armed_away
        - service: alarm_control_panel.alarm_arm_away
          entity_id:
            - alarm_control_panel.konnected_alarm
        - service: alarm_control_panel.alarm_arm_away
          entity_id:
            - alarm_control_panel.alexa_guard_7514f
        - service: climate.set_preset_mode
          entity_id:
            - climate.living_room
          data: {"preset_mode": "away"}
        - service: notify.alexa_media
          data:
            data:
              type: tts
            target:
            - group.alexa
            message: I'll start guarding now

  - konnectedhome:
      alias: 'Konnected Home'
      sequence:
        - service: input_select.select_option
          data:
            entity_id: input_select.konnectedstatus
            option: armed_home
        - service: alarm_control_panel.alarm_arm_home
          entity_id:
            - alarm_control_panel.konnected_alarm
        - service: alarm_control_panel.alarm_arm_home
          entity_id:
            - alarm_control_panel.alexa_guard_7514f

  - konnectedpending:
      alias: 'Konnected Pending'
      sequence:
        - service: alarm_control_panel.alarm_trigger
          entity_id: alarm_control_panel.Konnected_Alarm
        - service: notify.alexa_media
          data:
            data:
              type: tts
            target:
              - group.alexa
            message: Motion detected, the alarm will activate shortly. Motion detected, the alarm will activate shortly.

  - konnectedstandby:
      alias: 'Konnected Standby'
      sequence:
        - service: input_select.select_option
          data:
            entity_id: input_select.konnectedstatus
            option: disarmed
        - service: alarm_control_panel.alarm_disarm
          entity_id:
            - alarm_control_panel.konnected_alarm
        - service: alarm_control_panel.alarm_disarm
          entity_id:
            - alarm_control_panel.alexa_guard_7514f
        - service: climate.set_preset_mode
          entity_id:
            - climate.living_room
          data: {"preset_mode": "home"}

  - konnectedtrigger:
      alias: 'Konnected Trigger'
      sequence:
        - service: switch.turn_on
          entity_id: switch.siren
        - service: switch.turn_on
          entity_id: switch.backyard_siren
        - service: notify.alexa_media
          data:
            data:
              type: tts
            target:
              - group.alexa
            message: Your alarm was activated
        - service: notify.html5
          data:
            title: Konnected
            message: Your alarm was activated
            data:
              actions:
                - action: open
                  icon: "/local/icons/konnected.png"
                  title: Open Home Assistant
              tag: konnected-alarm-notification
              ttl: 86400
              priority: high      
        - service: notify.notify
          data:
            message: "Your alarm was activated"
            data:
              push:
                badge: 0
                category: alarm_control_panel.Konnected_Alarm

  - log_motion:
      alias: Log Motion
      sequence:
        - service: logbook.log
          data_template:
            name: "Motion detected: "
            message: >-
              {{ states[entityid.split('.')[0]][entityid.split('.')[1]].name }}      