homeassistant:
  customize:
    person.dennis:
      entity_picture: "/local/images/dennis-square.jpg"
    person.stephanie:
      entity_picture: "/local/images/stephanie-square.jpg"
    person.lucas:
      entity_picture: "/local/images/lucas-square.jpg"
    person.timo:
      entity_picture: "/local/images/timo-square.jpg"


group:
  household:
    - person.dennis
    - person.stephanie
    - person.lucas
    - person.timo

proximity:
  home:
    devices:
      - person.dennis
      - person.stephanie
    tolerance: 100
    unit_of_measurement: km

  dennis:
    devices:
      - person.dennis
    tolerance: 100
    unit_of_measurement: km

  stephanie:
    devices:
      - person.stephanie
    tolerance: 100
    unit_of_measurement: km

  lucas:
    devices:
      - person.lucas
    tolerance: 100
    unit_of_measurement: km

  timo:
    devices:
      - person.timo
    tolerance: 100
    unit_of_measurement: km
