group:
  household:
    - person.dennis
    - person.stephanie
    - person.lucas
    - person.timo

proximity:
  home:
    devices:
      - person.dennis
      - person.stephanie
    tolerance: 100
    unit_of_measurement: km

  dennis:
    devices:
      - person.dennis
    tolerance: 100
    unit_of_measurement: km

  stephanie:
    devices:
      - person.stephanie
    tolerance: 100
    unit_of_measurement: km

automation:
  - id: 9f06a214-339a-49bd-91ba-2e359a84538b
    alias: '[Presence] Lucas or Timo arriving at Gouvernantelaan'
    initial_state: 'true'
    condition:
      - condition: time
        after: '22:00:00'
        before: '07:00:00'
    trigger:
      - platform: zone
        entity_id:
            - person.lucas
            - person.timo
        zone: zone.gouvernantelaan
        event: enter
    action:
      - service: notify.mobile_app_dennis_galaxy
        data_template:
          message: "{{ trigger.to_state.name }} arrived at Gouvernantelaan at {{ states('sensor.time') }}"
          title: Presence detection

  - id: 416925c0-9e01-44e2-98b3-f9442d46e94e
    alias: '[Presence] Lucas or Timo left Gouvernantelaan'
    initial_state: 'true'
    # condition:
    #   - condition: time
    #     after: '22:00:00'
    #     before: '07:00:00'
    trigger:
      - platform: zone
        entity_id:
            - person.lucas
            - person.timo
        zone: zone.gouvernantelaan
        event: leave
    action:
      - service: notify.mobile_app_dennis_galaxy
        data_template:
          message: "{{ trigger.to_state.name }} left Gouvernantelaan at {{ states('sensor.time') }}"
          title: Presence detection
