input_select:
  house_mode:
    name: House mode
    options:
     - Morning
     - Day
     - Evening
     - Night
    icon: mdi:white-balance-sunny

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      # - 'time_date'
      # - 'time_utc'



automation:
  ###################################
  ##  Set to evening               ##
  ###################################
  - id: e684aed6-800b-42c3-8614-3f0079958a8e
    alias: '[House] Day Mode To Evening'
    initial_state: 'on'
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:45:00'

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.house_mode
          option: Evening

  ###################################
  ##  Set to morning               ##
  ###################################

  - id: 1d88c7c6-2720-4854-a2d3-9d48e36171a9
    alias: '[House] Day Mode To Morning'
    initial_state: 'on'
    trigger:
      - platform: sun
        event: sunrise

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.house_mode
          option: Morning

  # ###################################
  # ##  Set to day                   ##
  # ###################################

  - id: 1ee5fa81-d1a5-4f97-9941-61ca679d745c
    alias: '[House] Day Mode To Day'
    initial_state: 'on'
    trigger:
      - platform: time
        at: "09:00:00"

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.house_mode
          option: Day

  ###################################
  ##  Set to night                 ##
  ###################################

  - id: 126f8a12-ce80-45e7-a064-4764643ab0b7
    alias: '[House] Day Mode To Night'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.konnected_alarm
        to: 'armed_home'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.house_mode
          state: 'Evening'
        ## Has to be between 22 and 06
        - condition: time
          after: '22:00:00'
          before: '06:00:00'

        # ## Someone has to be home
        - condition: state
          entity_id: group.household
          state: 'home'
    action:
      - service: notify.mobile_app_sm_g960f
        data:
          message: 'It seems like everyone is asleep'
          title: 'Good night!'
      - service: input_select.select_option
        data:
          entity_id: input_select.house_mode
          option: Night
