weather:
  - platform: buienradar
    name: "Lopik-Cabauw"

sensor:
  - platform: buienradar
    monitored_conditions:
      - symbol
      - humidity
      - temperature
      - windforce
      - sunchance_1d
      - rainchance_1d
      - precipitation
      - conditionexact
      - conditionexact_1d
      - conditiondetailed
      - conditiondetailed_1d
      - condition_1d
      - condition_2d
      - condition_3d
      - condition_4d
      - condition_5d
  - platform: waqi
    token: !secret waqi_token
    locations:
      - Oude Meije, Zegveld

