weather:
  - platform: buienradar
    name: "Lopik-Cabauw"

sensor:
  - platform: buienradar
    monitored_conditions:
      - symbol
      - humidity
      - temperature
      - windforce
      - sunchance_1d
      - rainchance_1d
      - precipitation
      - conditionexact
      - conditionexact_1d
      - conditiondetailed
      - conditiondetailed_1d
      - condition_1d
      - condition_2d
      - condition_3d
      - condition_4d
      - condition_5d
  - platform: waqi
    token: !secret waqi_token
    locations:
      - Oude Meije, Zegveld

camera:
  - platform: generic
    name: Buienradar
    still_image_url: https://api.buienradar.nl/image/1.0/RadarMapNL?w=480&h=480
    content_type: 'image/gif'
  - platform: generic
    name: Meteogram
    still_image_url: !secret meteogram_png_url
  - platform: generic
    name: Waqi
    still_image_url: !secret waqi_png_url    