weather:
  - platform: buienradar
    name: "Lopik-Cabauw"

sensor:
  - platform: buienradar
    timeframe: 15
    monitored_conditions:
      - humidity
      - temperature
      - windforce
      - precipitation
      - precipitation_forecast_total
      - condition


