sensor:
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) }}'
  - platform: version
  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db
  - platform: rest
    resource: https://pypi.python.org/pypi/homeassistant/json
    name: Latest Version
    value_template: '{{ value_json.info.version }}'
    scan_interval: 3600

automation:
  - alias: '[System] Daily snapshot'
    initial_state: 'true'
    trigger:
    - platform: time
      at: '2:00:00'
    condition:
    - condition: state
      entity_id: person.dennis
      state: 'home'
    action:
    - data_template:
        name: Automated backup {{ now().strftime('%Y-%m-%d') }}
        password: !secret snapshot_password
      service: hassio.snapshot_full

  - alias: '[System] Update Notifications'
    initial_state: 'on'
    condition:
    - condition: template
      value_template: '{{ states.sensor.latest_version.state != states.sensor.current_version.state }}'
    trigger:
    - platform: time
      at: 04:00:00
    - platform: state
      entity_id: person.dennis
      from: 'not_home'
      to: 'home'
    action:
    - delay: 00:30:00
    - service: notify.html5_galaxy_s9
      data:
        title: Home Assistant Update
        message: "Version {{ states.sensor.latest_version.state }} is available!"
        target:
          - galaxy_s9_chrome
          - surfacebook_chrome