sensor:
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) }}'

  - platform: version

  - platform: rest
    resource: https://pypi.python.org/pypi/homeassistant/json
    name: Latest Version
    value_template: '{{ value_json.info.version }}'
    scan_interval: 3600

  - platform: command_line
    name: Supervisor updates
    command: 'curl http://supervisor/supervisor/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version,"addons":[.data.addons[] | select(.version != .installed)]}'''
    value_template: "{{ value_json.addons | length }}"
    json_attributes:
    - newest_version
    - current_version
    - addons

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot

  - platform: rest
    resource: http://10.0.20.10:8123/api/hassio/addons/a0d7b954_ssh/info
    name: 'SSH & Web Terminal'
    value_template: '{{ value_json.data.state }}'
    scan_interval: 60
    headers:
      Authorization: !secret llt
      Content-Type: application/json
    json_attributes_path: "$.data"
    json_attributes:
      - version
      - version_latest

  - platform: sql
    db_url: !secret recorder_db_url
    queries:
      - name: MariaDB size
        query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / POWER(1024,2), 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
        column: 'value'
        unit_of_measurement: MB

binary_sensor:
  - platform: template
    sensors:
      ssh_off:
        friendly_name: 'SSH & Web Terminal Add-on'
        device_class: power
        value_template: >
          {{ is_state('sensor.ssh_web_terminal', 'stopped') }}

alert:
  ssh_off:
    name: 'SSH & Web Terminal has stopped'
    entity_id: binary_sensor.ssh_off
    state: 'on'
    repeat:
      - 15
      - 30
      - 60
    can_acknowledge: true
    skip_first: false
    done_message: 'SSH & Web Terminal has started'
    notifiers:
      - mobile_app_sm_g986b
    data:
      tag: 'ssh-off'
      url: '/hassio/addon/a0d7b954_ssh/info'
