homeassistant:
  customize_glob:
    sensor.system_*:
      templates:
        icon_color: 
          if (state === 'Online') return 'white';
          else if (state === 'Unknown') return 'blue';
          else if (state === 'Offline') return 'red';

sensor:
  - platform: template
    sensors:
      system_hass_rpi:
        friendly_name: 'Hass RPi'
        icon_template: mdi:home-assistant
        entity_id: "device_tracker.raspberrypi"
        value_template: "{{ 'Online' }}"
      system_konnected:
        friendly_name: 'Konnected'
        icon_template: mdi:raspberry-pi
        entity_id: "device_tracker.konnected"
        value_template: "{{ 'Online' if is_state('device_tracker.konnected', 'home') else 'Offline' }}"
      system_vieratv:
        friendly_name: 'Living Room TV'
        icon_template: mdi:television
        entity_id: "device_tracker.living_room_tv"
        value_template: "{{ 'Online' if is_state('device_tracker.living_room_tv', 'home') else 'Offline' }}"
      system_samsungtv:
        friendly_name: 'Bedroom TV'
        icon_template: mdi:television
        entity_id: "device_tracker.master_bedroom_tv"
        value_template: "{{ 'Online' if is_state('device_tracker.master_bedroom_tv', 'home') else 'Offline' }}"
      system_firetvstick_living_room:
        friendly_name: 'Living Room Fire TV Stick'
        icon_template: mdi:cast
        entity_id: "device_tracker.living_room_fire_tv"
        value_template: "{{ 'Online' if is_state('device_tracker.living_room_fire_tv', 'home') else 'Offline' }}"
      system_firetvstick_master_bedroom:
        friendly_name: 'Master Bedroom Fire TV Stick'
        icon_template: mdi:cast
        entity_id: "device_tracker.master_bedroom_fire_tv"
        value_template: "{{ 'Online' if is_state('device_tracker.master_bedroom_fire_tv', 'home') else 'Offline' }}"
      system_ziggo_router:
        friendly_name: 'Ziggo Router'
        icon_template: mdi:wifi
        entity_id: "device_tracker.ziggo_router"
        value_template: "{{ 'Online' if is_state('device_tracker.ziggo_router', 'home') else 'Offline' }}"
      system_tplink_router:
        friendly_name: 'TP-Link Router'
        icon_template: mdi:wifi
        entity_id: "device_tracker.tplink_router"
        value_template: "{{ 'Online' if is_state('device_tracker.tplink_router', 'home') else 'Offline' }}"
      system_linksys_router:
        friendly_name: 'Linksys Router'
        icon_template: mdi:wifi
        entity_id: "device_tracker.linksys_router"
        value_template: "{{ 'Online' if is_state('device_tracker.linksys_router', 'home') else 'Offline' }}"
      system_powerline_router:
        friendly_name: 'Powerline Router'
        icon_template: mdi:wifi
        entity_id: "device_tracker.powerline_router"
        value_template: "{{ 'Online' if is_state('device_tracker.powerline_router', 'home') else 'Offline' }}"
      system_xbox_one:
        friendly_name: 'Xbox One'
        icon_template: mdi:xbox
        entity_id: "device_tracker.xbox_one"
        value_template: "{{ 'Online' if is_state('device_tracker.xbox_one', 'home') else 'Offline' }}"
      system_invoke:
        friendly_name: 'Invoke'
        icon_template: mdi:speaker
        entity_id: "device_tracker.invoke"
        value_template: "{{ 'Online' if is_state('device_tracker.invoke', 'home') else 'Offline' }}"
      system_ring_doorbell:
        friendly_name: 'Doorbell'
        icon_template: mdi:doorbell-video
        entity_id: "device_tracker.ring_doorbell"
        value_template: "{{ 'Online' if is_state('device_tracker.ring_doorbell', 'home') else 'Offline' }}"
      system_ring_backyard_cam:
        friendly_name: Backyard Cam
        icon_template: mdi:webcam
        entity_id: "device_tracker.ring_stickup"
        value_template: "{{ 'Online' if is_state('device_tracker.ring_stickup', 'home') else 'Offline' }}"
      system_ring_chime:
        friendly_name: 'Chime'
        icon_template: mdi:bell-outline
        entity_id: "device_tracker.ring_chime"
        value_template: "{{ 'Online' if is_state('device_tracker.ring_chime', 'home') else 'Offline' }}"
      system_living_room_thermostat:
        friendly_name: 'Thermostat'
        icon_template: mdi:thermostat
        entity_id: "device_tracker.nest_thermostat"
        value_template: "{{ 'Online' if is_state('device_tracker.nest_thermostat', 'home') else 'Offline' }}"
      system_entryway_smokeco:
        friendly_name: 'Entryway'
        icon_template: bha:smoke-detector
        entity_id: "device_tracker.entryway_protect"
        value_template: "{{ 'Online' if is_state('device_tracker.entryway_protect', 'home') else 'Offline' }}"
      system_hallway_smokeco:
        friendly_name: 'Hallway'
        icon_template: bha:smoke-detector
        entity_id: "device_tracker.hallway_protect"
        value_template: "{{ 'Online' if is_state('device_tracker.hallway_protect', 'home') else 'Offline' }}"
      system_attic_smokeco:
        friendly_name: 'Attic'
        icon_template: bha:smoke-detector
        entity_id: "device_tracker.attic_protect"
        value_template: "{{ 'Online' if is_state('device_tracker.attic_protect', 'home') else 'Offline' }}"
      system_living_room_echo_dot:
        friendly_name: 'Living Room'
        icon_template: mdi:amazon-alexa
        entity_id: "device_tracker.alexa_living_room"
        value_template: "{{ 'Online' if is_state('device_tracker.alexa_living_room', 'home') else 'Offline' }}"
      system_master_bedroom_echo_dot:
        friendly_name: 'Master Bedroom'
        icon_template: mdi:amazon-alexa
        entity_id: "device_tracker.alexa_master_bedroom"
        value_template: "{{ 'Online' if is_state('device_tracker.alexa_master_bedroom', 'home') else 'Offline' }}"
      system_lucas_bedroom_echo_dot:
        friendly_name: 'Lucas'
        icon_template: mdi:amazon-alexa
        entity_id: "device_tracker.alexa_lucas_bedroom"
        value_template: "{{ 'Online' if is_state('device_tracker.alexa_lucas_bedroom', 'home') else 'Offline' }}"
      system_timo_s_bedroom_echo_dot:
        friendly_name: 'Timo'
        icon_template: mdi:amazon-alexa
        entity_id: "device_tracker.alexa_timo_bedroom"
        value_template: "{{ 'Online' if is_state('device_tracker.alexa_timo_bedroom', 'home') else 'Offline' }}"
      system_emilie_s_bedroom_echo_dot:
        friendly_name: 'Emilie'
        icon_template: mdi:amazon-alexa
        entity_id: "device_tracker.alexa_emilie_bedroom"
        value_template: "{{ 'Online' if is_state('device_tracker.alexa_emilie_bedroom', 'home') else 'Offline' }}"

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload
