homeassistant:
  customize:
    sensor.system_magic_mirror_rpi:
      icon: mdi:raspberrypi
    sensor.system_dashboard_rpi:
      icon: mdi:raspberrypi
    sensor.system_hass_rpi:
      icon: mdi:home-assistant
    sensor.system_rpi_zero:
      icon: mdi:raspberrypi
    sensor.system_stefan_computer:
      icon: mdi:monitor
    sensor.system_isa_laptop:
      icon: mdi:laptop-windows
    sensor.system_isa_computer:
      icon: mdi:monitor
    sensor.system_printer:
      icon: mdi:printer
    sensor.system_nas:
      icon: mdi:server
    sensor.system_shield:
      icon: mdi:android
    # sensor.system_shield_2:
    #   icon: mdi:android
    sensor.system_ipad:
      icon: mdi:tablet-ipad
    sensor.system_movie_system:
      icon: mdi:speaker
    # sensor.system_hue_hub:
      # icon: mdi:lightbulb-outline
    sensor.system_ikea_gateway:
      icon: mdi:google-keep
    sensor.system_xiaomi_gateway:
      icon: mdi:circle-outline
    sensor.system_ip_camera:
      icon: mdi:webcam
    sensor.system_galaxy_tab:
      icon: mdi:tablet-android
    sensor.system_withings_scale:
      icon: mdi:scale-bathroom
    sensor.system_sonos_3:
      icon: mdi:speaker
    sensor.system_milight_hub:
      icon: mdi:google-keep
    sensor.system_isa_dell_xps:
      icon: mdi:laptop-windows
    sensor.system_stefan_laptop:
      icon: mdi:laptop-windows

  customize_glob:
    sensor.system_*:
      templates:
        hs_color: "if (state === 'Online') return [0, 0];
        else if (state === 'Unknown') return [40, 70];
        else if (state === 'Offline') return [0, 85];"    
      
sensor:
  - platform: template
    sensors:
        system_milight_hub:
          friendly_name: 'Milight Hub'
          entity_id: "device_tracker.milight_controller"
          value_template: "{{ 'Online' if is_state('device_tracker.milight_controller', 'home') else 'Offline' }}"
        system_nas:
          friendly_name: 'Synology NAS'
          entity_id: "device_tracker.synology_nas"
          value_template: "{{ 'Online' if is_state('device_tracker.synology_nas', 'home') else 'Offline' }}"
        system_vieratv:
          friendly_name: 'Living Room TV'
          icon_template: mdi:television
          entity_id: "device_tracker.living_room_tv"
          value_template: "{{ 'Online' if is_state('device_tracker.living_room_tv', 'home') else 'Offline' }}"
        system_samsungtv:
          friendly_name: 'Bedroom TV'
          icon_template: mdi:television
          entity_id: "device_tracker.master_bedroom_tv"
          value_template: "{{ 'Online' if is_state('device_tracker.bedroom_tv', 'home') else 'Offline' }}"
        system_firetvstick_living_room:
          friendly_name: 'Living Room Fire TV Stick'
          icon_template: mdi:cast
          entity_id: "device_tracker.living_room_fire_tv"
          value_template: "{{ 'Online' if is_state('device_tracker.living_room_fire_tv', 'home') else 'Offline' }}"
        system_firetvstick_master_bedroom:
          friendly_name: 'Master Bedroom Fire TV Stick'
          icon_template: mdi:cast
          entity_id: "device_tracker.master_bedroom_fire_tv"
          value_template: "{{ 'Online' if is_state('device_tracker.master_bedroom_fire_tv', 'home') else 'Offline' }}"
        system_ziggo_router:
          friendly_name: 'Ziggo Router'
          icon_template: mdi:wifi
          entity_id: "device_tracker.ziggo_router"
          value_template: "{{ 'Online' if is_state('device_tracker.ziggo_router', 'home') else 'Offline' }}"
        system_tplink_router:
          friendly_name: 'TP-Link Router'
          icon_template: mdi:wifi
          entity_id: "device_tracker.tplink_router"
          value_template: "{{ 'Online' if is_state('device_tracker.tplink_router', 'home') else 'Offline' }}"
        system_linksys_router:
          friendly_name: 'Linksys Router'
          icon_template: mdi:wifi
          entity_id: "device_tracker.linksys_router"
          value_template: "{{ 'Online' if is_state('device_tracker.linksys_router', 'home') else 'Offline' }}"
        system_powerline_router:
          friendly_name: 'Powerline Router'
          icon_template: mdi:wifi
          entity_id: "device_tracker.powerline_router"
          value_template: "{{ 'Online' if is_state('device_tracker.powerline_router', 'home') else 'Offline' }}"
        system_shield:
          friendly_name: 'NVidia Shield'
          entity_id: "device_tracker.nvidia_shield"
          value_template: "{{ 'Online' if is_state('device_tracker.nvidia_shield', 'home') else 'Offline' }}"
        # system_shield_2:
        #   friendly_name: 'NVidia Shield 2'
        #   entity_id: "device_tracker.shield"
        #   value_template: "{{ 'Online' if is_state('device_tracker.shield', 'home') else 'Offline' }}"
        system_xbox_one:
          friendly_name: 'Xbox One'
          icon_template: mdi:xbox
          entity_id: "device_tracker.xbox_one"
          value_template: "{{ 'Online' if is_state('device_tracker.xbox_one', 'home') else 'Offline' }}"
        system_stefan_computer:
          friendly_name: 'Stefan computer'
          entity_id: "device_tracker.stefan_computer"
          value_template: "{{ 'Online' if is_state('device_tracker.stefan_computer', 'home') else 'Offline' }}"
        system_stefan_laptop:
          friendly_name: 'Stefan laptop'
          entity_id: "device_tracker.cnstefang"
          value_template: "{{ 'Online' if is_state('device_tracker.cnstefang', 'home') else 'Offline' }}"
        system_isa_computer:
          friendly_name: 'Isas computer'
          entity_id: "device_tracker.isa_computer"
          value_template: "{{ 'Online' if is_state('device_tracker.isa_computer', 'home') else 'Offline' }}"
        system_isa_laptop:
          friendly_name: 'Isas old laptop'
          entity_id: "device_tracker.isa_laptop"
          value_template: "{{ 'Online' if is_state('device_tracker.isa_laptop', 'home') else 'Offline' }}"
        system_isa_dell_xps:
          friendly_name: 'Isa Dell XPS'
          entity_id: "device_tracker.desktop39i618g"
          value_template: "{{ 'Online' if is_state('device_tracker.desktop39i618g', 'home') else 'Offline' }}"        
        system_printer:
          friendly_name: 'HP Printer'
          entity_id: "device_tracker.hp_printer"
          value_template: "{{ 'Online' if is_state('device_tracker.hp_printer', 'home') else 'Offline' }}"
        system_ipad:
          friendly_name: 'iPad'
          entity_id: "device_tracker.paddan"
          value_template: "{{ 'Online' if is_state('device_tracker.paddan', 'home') else 'Offline' }}"
        system_asus_router:
          friendly_name: 'Asus Router'
          entity_id: "device_tracker.router_asus"
          value_template: "{{ 'Online' if is_state('device_tracker.router_asus', 'home') else 'Offline' }}"
        system_hass_rpi:
          friendly_name: 'Hass RPi'
          entity_id: "device_tracker.raspberrypi"
          value_template: "{{ 'Online' if is_state('device_tracker.raspberrypi', 'home') else 'Offline' }}"
        system_ring_doorbell:
          friendly_name: 'Doorbell'
          icon_template: mdi:doorbell-video
          entity_id: "device_tracker.ring_doorbell"
          value_template: "{{ 'Online' if is_state('device_tracker.ring_doorbell', 'home') else 'Offline' }}"
        system_ring_backyard_cam:
          friendly_name: Backyard Cam
          icon_template: mdi:webcam
          entity_id: "device_tracker.ring_stickup"
          value_template: "{{ 'Online' if is_state('device_tracker.ring_stickup', 'home') else 'Offline' }}"
        system_ring_chime:
          friendly_name: 'Chime'
          icon_template: mdi:bell-outline
          entity_id: "device_tracker.ring_chime"
          value_template: "{{ 'Online' if is_state('device_tracker.ring_chime', 'home') else 'Offline' }}"
        system_entryway_smokeco:
          friendly_name: 'Entryway Nest Protect'
          icon_template: bha:smoke-detector
          entity_id: "device_tracker.entryway_protect"
          value_template: "{{ 'Online' if is_state('device_tracker.entryway_protect', 'home') else 'Offline' }}"
        system_hallway_smokeco:
          friendly_name: 'Hallway Nest Protect'
          icon_template: bha:smoke-detector
          entity_id: "device_tracker.hallway_protect"
          value_template: "{{ 'Online' if is_state('device_tracker.hallway_protect', 'home') else 'Offline' }}"
        system_attic_smokeco:
          friendly_name: 'Attic Nest Protect'
          icon_template: bha:smoke-detector
          entity_id: "device_tracker.attic_protect"
          value_template: "{{ 'Online' if is_state('device_tracker.attic_protect', 'home') else 'Offline' }}"
        system_living_room_echo_dot:
          friendly_name: 'Living Room'
          icon_template: mdi:amazon-alexa
          entity_id: "device_tracker.38_f7_3d_36_bb_35"
          value_template: "{{ 'Online' if is_state('device_tracker.38_f7_3d_36_bb_35', 'home') else 'Offline' }}"
        system_master_bedroom_echo_dot:
          friendly_name: 'Master Bedroom'
          icon_template: mdi:amazon-alexa
          entity_id: "device_tracker.fc_a6_67_f7_a7_a8"
          value_template: "{{ 'Online' if is_state('device_tracker.fc_a6_67_f7_a7_a8', 'home') else 'Offline' }}"
        system_lucas_bedroom_echo_dot:
          friendly_name: 'Lucas'
          icon_template: mdi:amazon-alexa
          entity_id: "device_tracker.50_dc_e7_d3_96_9b"
          value_template: "{{ 'Online' if is_state('device_tracker.50_dc_e7_d3_96_9b', 'home') else 'Offline' }}"
        system_timo_s_bedroom_echo_dot:
          friendly_name: 'Timo'
          icon_template: mdi:amazon-alexa
          entity_id: "device_tracker.50_dc_e7_86_6b_b7"
          value_template: "{{ 'Online' if is_state('device_tracker.50_dc_e7_86_6b_b7', 'home') else 'Offline' }}"
        system_emilie_s_bedroom_echo_dot:
          friendly_name: 'Emilie'
          icon_template: mdi:amazon-alexa
          entity_id: "device_tracker.50_dc_e7_d1_65_55"
          value_template: "{{ 'Online' if is_state('device_tracker.50_dc_e7_d1_65_55', 'home') else 'Offline' }}"
automation:
  - alias: '[System] Device Status'
    initial_state: 'on'
    trigger:
         - platform: state
           entity_id:
            #   - sensor.system_ziggo_router
            #   - sensor.system_tplink_router
            #   - sensor.system_linksys_router
            #   - sensor.system_powerline_router
            #   - sensor.system_printer
            #   - sensor.system_nas
            #   # - sensor.system_hue_hub
            #   - sensor.system_ir_blaster
            #   - sensor.system_ir_blaster_bedroom
            #   - sensor.system_ip_camera
            # #  - sensor.system_ir_blaster_living_room
            #   - sensor.system_xiaomi_gateway
            #   - sensor.system_milight_hub
              - sensor.system_ring_doorbell
              - sensor.system_ring_chime
              # - sensor.system_axis_living_room
              # - sensor.system_dafang
              # - sensor.system_ip_camera
              
           to: 'Offline'
           for:
             minutes: 5
    action:
      - service: notify.html5_galaxy_s9
        data_template:
          title: 'Device {{ trigger.to_state.name }} is'
          message: >
            '{{ trigger.to_state.state }}'

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload
