sensor:
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) }}'
  - platform: version
  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db
  - platform: rest
    resource: https://pypi.python.org/pypi/homeassistant/json
    name: Latest Version
    value_template: '{{ value_json.info.version }}'
    scan_interval: 3600
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot

  # - platform: glances
  #   host: 127.0.0.1
  #   port: 61208
  #   name: "Nuc"
  #   ssl: true
  #   verify_ssl: false
  #   username: !secret glances_username
  #   password: !secret glances_password
  #   version: 3
  #   resources:
  #     - 'disk_use_percent'
  #     - 'memory_use_percent'
  #     - 'swap_use_percent'
  #     - 'processor_load'
  #     - 'docker_active'
  #     - 'docker_cpu_use'


automation:
  - alias: '[System] Daily snapshot'
    initial_state: 'true'
    trigger:
    - platform: time
      at: '2:00:00'
    condition:
    - condition: state
      entity_id: person.dennis
      state: 'home'
    action:
    - data_template:
        name: Automated backup {{ now().strftime('%Y-%m-%d') }}
        password: !secret snapshot_password
      service: hassio.snapshot_full

  - alias: '[System] Update Notifications'
    initial_state: 'on'
    condition:
    - condition: template
      value_template: '{{ states.sensor.latest_version.state != states.sensor.current_version.state }}'
    trigger:
    - platform: time
      at: 04:00:00
    - platform: state
      entity_id: person.dennis
      from: 'not_home'
      to: 'home'
    action:
    - delay: 00:30:00
    - service: notify.html5_galaxy_s9
      data:
        title: Home Assistant Update
        message: "Version {{ states.sensor.latest_version.state }} is available!"
        target:
          - galaxy_s9_chrome
          - surfacebook_chrome

  # - alias: '[System] Hass Started'
  #   initial_state: 'on'
  #   trigger:
  #     platform: homeassistant
  #     event: start
  #   action:
  #     - service: notify.discord_system_hook
  #       data:
  #         message: "@here Hass.io Online"
  #     - service: mqtt.publish
  #       data:
  #         topic: monitor/scan/arrive

  # - alias: '[System] Hass Ready'
  #   initial_state: 'on'
  #   trigger:
  #     platform: event
  #     event_type: zwave.network_ready
  #   action:
  #     - service: notify.discord_system_hook
  #       data:
  #         message: "Z-wave network now ready"
  #     - delay: 00:05
  #     - service: homekit.start
      
  # - alias: '[System] Hass Stopped'
  #   initial_state: 'on'
  #   trigger:
  #     platform: homeassistant
  #     event: shutdown
  #   action:
  #     - service: notify.discord_system_hook
  #       data:
  #         message: "@here Hass.io Offline"
        
  # - alias: '[System] Hass New Device Tracked'
  #   initial_state: 'on'
  #   trigger:
  #     platform: event
  #     event_type: device_tracker_new_device
  #   action:
  #     - service: notify.discord_system_hook
  #       data_template:
  #         message: >
  #           New Device Tracked: {{trigger.event.data.host_name}} ({{trigger.event.data.entity_id}})

  # - alias: '[System] Hass New Platform Discovered'
  #   initial_state: 'on'
  #   trigger:
  #     platform: event
  #     event_type: PLATFORM_DISCOVERED
  #   action:
  #     - service: notify.discord_system_hook
  #       data_template:
  #         message: >
  #           New Platform Discovered: {{trigger.event.data.service}} ({{trigger.event.data.discovered}})

  # - alias: '[System] Ip Ban Notify'
  #   initial_state: 'on'
  #   trigger:
  #     - platform: state
  #       entity_id: persistent_notification.ipban
  #   condition:
  #     - condition: template
  #       value_template: "{{ trigger.to_state.state != off }}"
  #   action:
  #     - service: notify.discord_system_hook
  #       data_template:
  #         message: >
  #           '@here {{ trigger.state.attributes.message }}. Ip address has been banned.'
